from __future__ import annotations

from libs import pypi_library, replace_text_once, source_path, transform_source_text, write_source_text


def embed_jupyter_events_schemas(context) -> None:
    package_root = source_path(context, "Lib/jupyter_events")
    schema_text = {
        path.relative_to(package_root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted((package_root / "schemas").rglob("*"))
        if path.is_file()
    }

    write_source_text(
        context,
        "Lib/jupyter_events/_static_schemas.py",
        "# Generated by StaticPython to keep Jupyter Events schema loads working after freezing.\n"
        + "SCHEMA_TEXT = "
        + repr(schema_text)
        + "\n",
    )

    def patch_validators(text: str) -> str:
        text = replace_text_once(
            text,
            "from . import yaml\n",
            "from . import yaml\nfrom ._static_schemas import SCHEMA_TEXT as _STATICPYTHON_SCHEMA_TEXT\n",
            label="jupyter_events static schema import",
        )
        text = replace_text_once(
            text,
            "EVENT_METASCHEMA = yaml.load(EVENT_METASCHEMA_FILEPATH)\n",
            'EVENT_METASCHEMA = yaml.loads(_STATICPYTHON_SCHEMA_TEXT["schemas/event-metaschema.yml"])\n',
            label="jupyter_events event metaschema",
        )
        text = replace_text_once(
            text,
            "EVENT_CORE_SCHEMA = yaml.load(EVENT_CORE_SCHEMA_FILEPATH)\n",
            'EVENT_CORE_SCHEMA = yaml.loads(_STATICPYTHON_SCHEMA_TEXT["schemas/event-core-schema.yml"])\n',
            label="jupyter_events core schema",
        )
        return replace_text_once(
            text,
            "PROPERTY_METASCHEMA = yaml.load(PROPERTY_METASCHEMA_FILEPATH)\n",
            'PROPERTY_METASCHEMA = yaml.loads(_STATICPYTHON_SCHEMA_TEXT["schemas/property-metaschema.yml"])\n',
            label="jupyter_events property metaschema",
        )

    transform_source_text(context, "Lib/jupyter_events/validators.py", patch_validators)

    def patch_yaml(text: str) -> str:
        text = replace_text_once(
            text,
            "from pathlib import Path\n\n",
            "from pathlib import Path\n\nfrom ._static_schemas import SCHEMA_TEXT as _STATICPYTHON_SCHEMA_TEXT\n\n",
            label="jupyter_events yaml static schema import",
        )
        return replace_text_once(
            text,
            "    data = Path(str(fpath)).read_text(encoding=\"utf-8\")\n"
            "    return loads(data)\n",
            "    path_text = str(fpath).replace('\\\\', '/')\n"
            "    marker = '/jupyter_events/schemas/'\n"
            "    if marker in path_text:\n"
            "        resource_key = 'schemas/' + path_text.rsplit(marker, 1)[1]\n"
            "        data = _STATICPYTHON_SCHEMA_TEXT.get(resource_key)\n"
            "        if data is not None:\n"
            "            return loads(data)\n"
            "    data = Path(str(fpath)).read_text(encoding=\"utf-8\")\n"
            "    return loads(data)\n",
            label="jupyter_events yaml embedded schema loader",
        )

    def patch_schema(text: str) -> str:
        text = replace_text_once(
            text,
            "from . import yaml\n",
            "from . import yaml\nfrom ._static_schemas import SCHEMA_TEXT as _STATICPYTHON_SCHEMA_TEXT\n",
            label="jupyter_events schema static import",
        )
        return replace_text_once(
            text,
            "            if not Path(schema).exists():\n"
            "                msg = f'Schema file not present at path \"{schema}\".'\n"
            "                raise EventSchemaFileAbsent(msg)\n"
            "\n"
            "            loaded_schema = yaml.load(schema)\n",
            "            path_text = str(schema).replace('\\\\', '/')\n"
            "            marker = '/jupyter_events/schemas/'\n"
            "            static_schema = None\n"
            "            if marker in path_text:\n"
            "                resource_key = 'schemas/' + path_text.rsplit(marker, 1)[1]\n"
            "                static_schema = _STATICPYTHON_SCHEMA_TEXT.get(resource_key)\n"
            "            if static_schema is None and not Path(schema).exists():\n"
            "                msg = f'Schema file not present at path \"{schema}\".'\n"
            "                raise EventSchemaFileAbsent(msg)\n"
            "\n"
            "            loaded_schema = yaml.loads(static_schema) if static_schema is not None else yaml.load(schema)\n",
            label="jupyter_events schema embedded path loader",
        )

    transform_source_text(context, "Lib/jupyter_events/yaml.py", patch_yaml)
    transform_source_text(context, "Lib/jupyter_events/schema.py", patch_schema)


LIBRARY_INTEGRATION = pypi_library(
    name="jupyter_events",
    project_name="jupyter-events",
    release_version="0.6.3",
    source_mapping={
        "jupyter_events": "Lib/jupyter_events",
    },
    python_packages=["jupyter_events"],
    post_patch_hooks=[embed_jupyter_events_schemas],
)
