from __future__ import annotations

from libs import inline_verification_step, pypi_library, replace_text_once, source_path, transform_source_text, write_source_text


def embed_jupyter_events_schemas(context) -> None:
    package_root = source_path(context, "Lib/jupyter_events")
    schema_text = {
        path.relative_to(package_root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted((package_root / "schemas").rglob("*"))
        if path.is_file()
    }

    write_source_text(
        context,
        "Lib/jupyter_events/_static_schemas.py",
        "# Generated by StaticPython to keep Jupyter Events schema loads working after freezing.\n"
        + "SCHEMA_TEXT = "
        + repr(schema_text)
        + "\n",
    )

    def patch_validators(text: str) -> str:
        text = replace_text_once(
            text,
            "from . import yaml\n",
            "from . import yaml\nfrom ._static_schemas import SCHEMA_TEXT as _STATICPYTHON_SCHEMA_TEXT\n",
            label="jupyter_events static schema import",
        )
        text = replace_text_once(
            text,
            "EVENT_METASCHEMA = yaml.load(EVENT_METASCHEMA_FILEPATH)\n",
            'EVENT_METASCHEMA = yaml.loads(_STATICPYTHON_SCHEMA_TEXT["schemas/event-metaschema.yml"])\n',
            label="jupyter_events event metaschema",
        )
        text = replace_text_once(
            text,
            "EVENT_CORE_SCHEMA = yaml.load(EVENT_CORE_SCHEMA_FILEPATH)\n",
            'EVENT_CORE_SCHEMA = yaml.loads(_STATICPYTHON_SCHEMA_TEXT["schemas/event-core-schema.yml"])\n',
            label="jupyter_events core schema",
        )
        return replace_text_once(
            text,
            "PROPERTY_METASCHEMA = yaml.load(PROPERTY_METASCHEMA_FILEPATH)\n",
            'PROPERTY_METASCHEMA = yaml.loads(_STATICPYTHON_SCHEMA_TEXT["schemas/property-metaschema.yml"])\n',
            label="jupyter_events property metaschema",
        )

    transform_source_text(context, "Lib/jupyter_events/validators.py", patch_validators)


LIBRARY_INTEGRATION = pypi_library(
    name="jupyter_events",
    project_name="jupyter-events",
    release_version="0.6.3",
    source_mapping={
        "jupyter_events": "Lib/jupyter_events",
    },
    python_packages=["jupyter_events"],
    post_patch_hooks=[embed_jupyter_events_schemas],
    verification_steps=[
        inline_verification_step(
            "jupyter-events-smoke",
            """
import io
import json
import logging

from jupyter_events import EventLogger, EventSchema
from jupyter_events.validators import EVENT_CORE_SCHEMA, EVENT_METASCHEMA, PROPERTY_METASCHEMA, validate_schema
from pythonjsonlogger import jsonlogger

assert EVENT_METASCHEMA["$id"].startswith("http://event.jupyter.org/")
assert EVENT_CORE_SCHEMA["$id"].startswith("http://event.jupyter.org/")
assert PROPERTY_METASCHEMA["$id"].startswith("http://event.jupyter.org/")

schema = {
    "$id": "https://events.example.com/staticpython/demo",
    "$schema": EVENT_METASCHEMA["$id"],
    "version": 1,
    "title": "StaticPython demo event",
    "description": "Smoke test schema.",
    "type": "object",
    "properties": {
        "status": {"type": "string"},
        "value": {"type": "integer"},
    },
    "required": ["status"],
    "additionalProperties": False,
}

validate_schema(schema)
event_schema = EventSchema(schema)
assert event_schema.id == schema["$id"]

stream = io.StringIO()
handler = logging.StreamHandler(stream)
logger = EventLogger()
logger.register_handler(handler)
assert isinstance(handler.formatter, jsonlogger.JsonFormatter)
logger.register_event_schema(schema)
assert schema["$id"] in logger.schemas.schema_ids

capsule = logger.emit(schema_id=schema["$id"], data={"status": "ok", "value": 42})
handler.flush()
payload = json.loads(stream.getvalue())

assert capsule["__schema__"] == schema["$id"]
assert payload["status"] == "ok"
assert payload["value"] == 42
assert payload["__schema__"] == schema["$id"]
assert payload["__metadata_version__"] == 1
""",
        )
    ],
)
