from __future__ import annotations

import base64
import re

from libs import simple_library, source_path, transform_source_text, write_source_text


def embed_babel_data(context) -> None:
    package_root = source_path(context, "Lib/babel")
    locale_data_root = package_root / "locale-data"
    if not locale_data_root.exists():
        locale_data_root = package_root / "localedata"
    locale_data = {
        path.stem: base64.b64encode(path.read_bytes()).decode("ascii")
        for path in sorted(locale_data_root.glob("*.dat"))
    }
    global_data = base64.b64encode((package_root / "global.dat").read_bytes()).decode("ascii")
    if not locale_data or "root" not in locale_data:
        raise RuntimeError("expected Babel locale-data files were not materialized")

    write_source_text(
        context,
        "Lib/babel/_staticpython_data.py",
        "# Generated by StaticPython; keeps Babel data files available after freezing.\n"
        "import base64\n\n"
        f"GLOBAL_DATA = {global_data!r}\n"
        f"LOCALE_DATA = {locale_data!r}\n\n"
        "def global_bytes() -> bytes:\n"
        "    return base64.b64decode(GLOBAL_DATA)\n\n"
        "def locale_bytes(name: str) -> bytes:\n"
        "    return base64.b64decode(LOCALE_DATA[name])\n",
    )

    def patch_core(text: str) -> str:
        if "_staticpython_global_bytes" not in text:
            anchor = "from babel import localedata\n"
            if anchor not in text:
                raise RuntimeError("expected 'from babel import localedata' in babel.core")
            text = text.replace(
                anchor,
                anchor + "from babel._staticpython_data import global_bytes as _staticpython_global_bytes\n",
                1,
            )
        if "pickle.loads(_staticpython_global_bytes())" in text:
            return text
        updated, count = re.subn(
            r"(?ms)^def get_global\(.*?(?=^LOCALE_ALIASES =)",
            "def get_global(key):\n"
            "    \"\"\"Return the dictionary for the given key in the global data.\"\"\"\n"
            "    global _global_data\n"
            "    if _global_data is None:\n"
            "        _global_data = pickle.loads(_staticpython_global_bytes())\n"
            "        assert _global_data is not None\n"
            "    return _global_data.get(key, {})\n\n",
            text,
            count=1,
        )
        if count != 1:
            raise RuntimeError("expected get_global() implementation in babel.core")
        return updated

    def patch_localedata(text: str) -> str:
        if "_STATICPYTHON_LOCALE_DATA" not in text:
            if "except ImportError:\n    import dummy_threading as threading\n" in text:
                text = text.replace(
                    "except ImportError:\n    import dummy_threading as threading\n",
                    "except ImportError:\n    import dummy_threading as threading\n"
                    "from babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\n"
                    "from babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
                    1,
                )
            elif "from typing import Any\n" in text:
                text = text.replace(
                    "from typing import Any\n",
                    "from typing import Any\n\n"
                    "from babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\n"
                    "from babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
                    1,
                )
            else:
                anchor = "import threading\n"
                if anchor not in text:
                    raise RuntimeError("expected threading import block in babel.localedata")
                text = text.replace(
                    anchor,
                    anchor
                    + "from babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\n"
                    + "from babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
                    1,
                )
        updated, count = re.subn(
            r"(?ms)^def exists\(.*?(?=^(?:@lru_cache\(maxsize=None\)\n)?def (?:locale_identifiers|list)\()",
            "def exists(name):\n"
            "    \"\"\"Check whether locale data is available for the given locale.\"\"\"\n"
            "    if not name:\n"
            "        return False\n"
            "    if name in _STATICPYTHON_LOCALE_DATA:\n"
            "        return True\n"
            "    if name in _cache:\n"
            "        return True\n"
            "    resolver = globals().get('resolve_locale_filename')\n"
            "    if callable(resolver):\n"
            "        file_found = os.path.exists(resolver(name))\n"
            "    else:\n"
            "        file_found = os.path.exists(os.path.join(_dirname, '%s.dat' % name))\n"
            "    normalize = globals().get('normalize_locale')\n"
            "    if callable(normalize):\n"
            "        return True if file_found else bool(normalize(name))\n"
            "    return file_found\n\n",
            text,
            count=1,
        )
        if count != 1:
            raise RuntimeError("expected exists() implementation in babel.localedata")
        text = updated
        if "def locale_identifiers(" in text:
            updated, count = re.subn(
                r"(?ms)^(?:@lru_cache\(maxsize=None\)\n)?def locale_identifiers\(.*?(?=^def _is_non_likely_script\()",
                "@lru_cache(maxsize=None)\n"
                "def locale_identifiers():\n"
                "    \"\"\"Return all locale identifiers that have data available.\"\"\"\n"
                "    if _STATICPYTHON_LOCALE_DATA:\n"
                "        return sorted(name for name in _STATICPYTHON_LOCALE_DATA if name != 'root')\n"
                "    return [\n"
                "        stem\n"
                "        for stem, extension in (\n"
                "            os.path.splitext(filename) for filename in os.listdir(_dirname)\n"
                "        )\n"
                "        if extension == '.dat' and stem != 'root'\n"
                "    ]\n\n",
                text,
                count=1,
            )
            if count != 1:
                raise RuntimeError("expected locale_identifiers() implementation in babel.localedata")
            text = updated
        else:
            updated, count = re.subn(
                r"(?ms)^def list\(.*?(?=^def load\()",
                "def list():\n"
                "    \"\"\"Return all locale identifiers that have data available.\"\"\"\n"
                "    if _STATICPYTHON_LOCALE_DATA:\n"
                "        return sorted(name for name in _STATICPYTHON_LOCALE_DATA if name != 'root')\n"
                "    return [stem for stem, extension in [\n"
                "        os.path.splitext(filename) for filename in os.listdir(_dirname)\n"
                "    ] if extension == '.dat' and stem != 'root']\n\n",
                text,
                count=1,
            )
            if count != 1:
                raise RuntimeError("expected list() implementation in babel.localedata")
            text = updated
        updated, count = re.subn(
            r"(?ms)^def load\(.*?(?=^def merge\()",
            "def load(name, merge_inherited=True):\n"
            "    \"\"\"Load the locale data for the given locale.\"\"\"\n"
            "    name = os.path.basename(name)\n"
            "    _cache_lock.acquire()\n"
            "    try:\n"
            "        data = _cache.get(name)\n"
            "        if not data:\n"
            "            if name == 'root' or not merge_inherited:\n"
            "                data = {}\n"
            "            else:\n"
            "                parent = None\n"
            "                try:\n"
            "                    from babel.core import get_global as _staticpython_get_global\n"
            "                except Exception:\n"
            "                    _staticpython_get_global = None\n"
            "                if _staticpython_get_global is not None:\n"
            "                    try:\n"
            "                        parent = _staticpython_get_global('parent_exceptions').get(name)\n"
            "                    except Exception:\n"
            "                        parent = None\n"
            "                if not parent:\n"
            "                    non_likely_script = globals().get('_is_non_likely_script')\n"
            "                    if callable(non_likely_script) and non_likely_script(name):\n"
            "                        parent = 'root'\n"
            "                    else:\n"
            "                        parts = name.split('_')\n"
            "                        parent = 'root' if len(parts) == 1 else '_'.join(parts[:-1])\n"
            "                data = load(parent).copy()\n"
            "            if name in _STATICPYTHON_LOCALE_DATA:\n"
            "                loaded = pickle.loads(_staticpython_locale_bytes(name))\n"
            "            else:\n"
            "                resolver = globals().get('resolve_locale_filename')\n"
            "                if callable(resolver):\n"
            "                    filename = resolver(name)\n"
            "                else:\n"
            "                    filename = os.path.join(_dirname, '%s.dat' % name)\n"
            "                fileobj = open(filename, 'rb')\n"
            "                try:\n"
            "                    loaded = pickle.load(fileobj)\n"
            "                finally:\n"
            "                    fileobj.close()\n"
            "            if name != 'root' and merge_inherited:\n"
            "                merge(data, loaded)\n"
            "            else:\n"
            "                data = loaded\n"
            "            _cache[name] = data\n"
            "        return data\n"
            "    finally:\n"
            "        _cache_lock.release()\n\n",
            text,
            count=1,
        )
        if count != 1:
            raise RuntimeError("expected load() implementation in babel.localedata")
        return updated

    transform_source_text(context, "Lib/babel/core.py", patch_core)
    transform_source_text(context, "Lib/babel/localedata.py", patch_localedata)


LIBRARY_INTEGRATION = simple_library(
    name="babel",
    project_name="Babel",
    overlay_entries=["Lib/babel"],
    materialized_paths=[
        "Lib/babel/global.dat",
        "Lib/babel/_staticpython_data.py",
    ],
    post_patch_hooks=[embed_babel_data],
)
