from __future__ import annotations

import base64
import pickle
import re
from packaging.version import Version

from libs import (
    _candidate_pypi_archives,
    _copy_entry,
    _download_file,
    _extract_archive,
    _resolve_source_entry,
    replace_function_block_once,
    simple_library,
    source_path,
    transform_source_text,
    write_source_text,
)


def _replace_block_before(text: str, marker: str, replacement: str, *, label: str) -> str:
    if replacement in text:
        return text
    start = text.find(marker)
    if start == -1:
        raise RuntimeError(f"expected marker not found in {label}: {marker!r}")
    block_start = text.rfind("\ndef ", 0, start)
    if block_start == -1:
        raise RuntimeError(f"expected function block before marker in {label}: {marker!r}")
    return text[: block_start + 1] + replacement + text[start:]


def _infer_babel_release_version(package_root) -> str | None:
    init_path = package_root / "__init__.py"
    if not init_path.exists():
        return None
    match = re.search(r"""__version__\s*=\s*['"]([^'"]+)['"]""", init_path.read_text(encoding="utf-8"))
    if match is None:
        return None
    return match.group(1)


def _materialize_babel_data_from_pure_wheel(context, package_root) -> bool:
    release_version = _infer_babel_release_version(package_root)
    if not release_version:
        return False

    candidates = _candidate_pypi_archives(
        context.download_cache_root,
        "Babel",
        Version(context.version_full),
        release_version,
    )
    for resolved_release_version, archive_path, url, _cached in candidates:
        if archive_path.suffix.lower() != ".whl":
            continue
        if not archive_path.exists():
            assert url is not None
            context.log(f"downloading Babel {resolved_release_version} fallback wheel from PyPI")
            _download_file(url, archive_path)
        extracted_root = _extract_archive(
            archive_path,
            context.work_cache_root / "pypi" / "babel" / resolved_release_version / "fallback-wheel" / archive_path.stem,
            context.log,
        )
        try:
            locale_src = _resolve_source_entry(extracted_root, "babel/locale-data")
        except RuntimeError:
            try:
                locale_src = _resolve_source_entry(extracted_root, "babel/localedata")
            except RuntimeError:
                locale_src = None
        try:
            global_src = _resolve_source_entry(extracted_root, "babel/global.dat")
        except RuntimeError:
            global_src = None

        if locale_src is not None:
            target_name = "locale-data" if locale_src.name == "locale-data" else locale_src.name
            _copy_entry(locale_src, package_root / target_name)
            context.log(
                f"materialized Babel locale data from fallback wheel {archive_path.name}"
            )
        if global_src is not None:
            _copy_entry(global_src, package_root / "global.dat")
            context.log(
                f"materialized Babel global.dat from fallback wheel {archive_path.name}"
            )
        if locale_src is not None:
            return True
    return False


def embed_babel_data(context) -> None:
    package_root = source_path(context, "Lib/babel")
    locale_data_root = package_root / "locale-data"
    if not locale_data_root.exists():
        locale_data_root = package_root / "localedata"
    if not locale_data_root.exists():
        _materialize_babel_data_from_pure_wheel(context, package_root)
        locale_data_root = package_root / "locale-data"
        if not locale_data_root.exists():
            locale_data_root = package_root / "localedata"
    global_data_path = package_root / "global.dat"
    locale_data = {
        path.stem: base64.b64encode(path.read_bytes()).decode("ascii")
        for path in sorted(locale_data_root.glob("*.dat"))
    }
    global_data = base64.b64encode(global_data_path.read_bytes()).decode("ascii") if global_data_path.exists() else ""
    if not locale_data or "root" not in locale_data:
        context.log("Babel locale data is unavailable for this release; generating a minimal embedded root locale")
        locale_data = {
            "root": base64.b64encode(pickle.dumps({})).decode("ascii"),
        }
    if not global_data:
        global_data = base64.b64encode(pickle.dumps({})).decode("ascii")

    write_source_text(
        context,
        "Lib/babel/_staticpython_data.py",
        "# Generated by StaticPython; keeps Babel data files available after freezing.\n"
        "import base64\n\n"
        f"GLOBAL_DATA = {global_data!r}\n"
        f"LOCALE_DATA = {locale_data!r}\n\n"
        "def global_bytes() -> bytes:\n"
        "    return base64.b64decode(GLOBAL_DATA)\n\n"
        "def locale_bytes(name: str) -> bytes:\n"
        "    return base64.b64decode(LOCALE_DATA[name])\n",
    )

    def patch_core(text: str) -> str:
        if "_staticpython_global_bytes" not in text:
            anchor = "from babel import localedata\n"
            if anchor not in text:
                raise RuntimeError("expected 'from babel import localedata' in babel.core")
            text = text.replace(
                anchor,
                anchor
                + "try:\n"
                + "    from babel._staticpython_data import global_bytes as _staticpython_global_bytes\n"
                + "except Exception:\n"
                + "    _staticpython_global_bytes = None\n",
                1,
            )
        if "pickle.loads(_staticpython_global_bytes())" in text or "_staticpython_global_bytes is None" in text:
            return text
        return _replace_block_before(
            text,
            "LOCALE_ALIASES =",
            "def get_global(key):\n"
            "    \"\"\"Return the dictionary for the given key in the global data.\"\"\"\n"
            "    global _global_data\n"
            "    if _global_data is None:\n"
            "        if _staticpython_global_bytes is not None:\n"
            "            _global_data = pickle.loads(_staticpython_global_bytes())\n"
            "        else:\n"
            "            filename = os.path.join(os.path.dirname(__file__), 'global.dat')\n"
            "            fileobj = open(filename, 'rb')\n"
            "            try:\n"
            "                _global_data = pickle.load(fileobj)\n"
            "            finally:\n"
            "                fileobj.close()\n"
            "        assert _global_data is not None\n"
            "    return _global_data.get(key, {})\n\n",
            label="babel.core get_global",
        )

    def patch_localedata(text: str) -> str:
        if "_STATICPYTHON_LOCALE_DATA" not in text:
            if "except ImportError:\n    import dummy_threading as threading\n" in text:
                text = text.replace(
                    "except ImportError:\n    import dummy_threading as threading\n",
                    "except ImportError:\n    import dummy_threading as threading\n"
                    "from babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\n"
                    "from babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
                    1,
                )
            elif "from typing import Any\n" in text:
                text = text.replace(
                    "from typing import Any\n",
                    "from typing import Any\n\n"
                    "from babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\n"
                    "from babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
                    1,
                )
            else:
                anchor = "import threading\n"
                if anchor not in text:
                    raise RuntimeError("expected threading import block in babel.localedata")
                text = text.replace(
                    anchor,
                    anchor
                    + "from babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\n"
                    + "from babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
                    1,
                )
        text = replace_function_block_once(
            text,
            "exists",
            "def exists(name):\n"
            "    \"\"\"Check whether locale data is available for the given locale.\"\"\"\n"
            "    if not name:\n"
            "        return False\n"
            "    if name in _STATICPYTHON_LOCALE_DATA:\n"
            "        return True\n"
            "    if name in _cache:\n"
            "        return True\n"
            "    resolver = globals().get('resolve_locale_filename')\n"
            "    if callable(resolver):\n"
            "        file_found = os.path.exists(resolver(name))\n"
            "    else:\n"
            "        file_found = os.path.exists(os.path.join(_dirname, '%s.dat' % name))\n"
            "    normalize = globals().get('normalize_locale')\n"
            "    if callable(normalize):\n"
            "        return True if file_found else bool(normalize(name))\n"
            "    return file_found\n\n",
            label="babel.localedata exists",
            next_name="locale_identifiers" if "def locale_identifiers(" in text else "list",
        )
        if "def locale_identifiers(" in text:
            next_name = "_is_non_likely_script" if "def _is_non_likely_script(" in text else "load"
            text = replace_function_block_once(
                text,
                "locale_identifiers",
                "@lru_cache(maxsize=None)\n"
                "def locale_identifiers():\n"
                "    \"\"\"Return all locale identifiers that have data available.\"\"\"\n"
                "    if _STATICPYTHON_LOCALE_DATA:\n"
                "        return sorted(name for name in _STATICPYTHON_LOCALE_DATA if name != 'root')\n"
                "    return [\n"
                "        stem\n"
                "        for stem, extension in (\n"
                "            os.path.splitext(filename) for filename in os.listdir(_dirname)\n"
                "        )\n"
                "        if extension == '.dat' and stem != 'root'\n"
                "    ]\n\n",
                label="babel.localedata locale_identifiers",
                next_name=next_name,
            )
        else:
            text = replace_function_block_once(
                text,
                "list",
                "def list():\n"
                "    \"\"\"Return all locale identifiers that have data available.\"\"\"\n"
                "    if _STATICPYTHON_LOCALE_DATA:\n"
                "        return sorted(name for name in _STATICPYTHON_LOCALE_DATA if name != 'root')\n"
                "    return [stem for stem, extension in [\n"
                "        os.path.splitext(filename) for filename in os.listdir(_dirname)\n"
                "    ] if extension == '.dat' and stem != 'root']\n\n",
                label="babel.localedata list",
                next_name="load",
            )
        return replace_function_block_once(
            text,
            "load",
            "def load(name, merge_inherited=True):\n"
            "    \"\"\"Load the locale data for the given locale.\"\"\"\n"
            "    name = os.path.basename(name)\n"
            "    _cache_lock.acquire()\n"
            "    try:\n"
            "        data = _cache.get(name)\n"
            "        if not data:\n"
            "            if name == 'root' or not merge_inherited:\n"
            "                data = {}\n"
            "            else:\n"
            "                parent = None\n"
            "                try:\n"
            "                    from babel.core import get_global as _staticpython_get_global\n"
            "                except Exception:\n"
            "                    _staticpython_get_global = None\n"
            "                if _staticpython_get_global is not None:\n"
            "                    try:\n"
            "                        parent = _staticpython_get_global('parent_exceptions').get(name)\n"
            "                    except Exception:\n"
            "                        parent = None\n"
            "                if not parent:\n"
            "                    non_likely_script = globals().get('_is_non_likely_script')\n"
            "                    if callable(non_likely_script) and non_likely_script(name):\n"
            "                        parent = 'root'\n"
            "                    else:\n"
            "                        parts = name.split('_')\n"
            "                        parent = 'root' if len(parts) == 1 else '_'.join(parts[:-1])\n"
            "                data = load(parent).copy()\n"
            "            if name in _STATICPYTHON_LOCALE_DATA:\n"
            "                loaded = pickle.loads(_staticpython_locale_bytes(name))\n"
            "            else:\n"
            "                resolver = globals().get('resolve_locale_filename')\n"
            "                if callable(resolver):\n"
            "                    filename = resolver(name)\n"
            "                else:\n"
            "                    filename = os.path.join(_dirname, '%s.dat' % name)\n"
            "                fileobj = open(filename, 'rb')\n"
            "                try:\n"
            "                    loaded = pickle.load(fileobj)\n"
            "                finally:\n"
            "                    fileobj.close()\n"
            "            if name != 'root' and merge_inherited:\n"
            "                merge(data, loaded)\n"
            "            else:\n"
            "                data = loaded\n"
            "            _cache[name] = data\n"
            "        return data\n"
            "    finally:\n"
            "        _cache_lock.release()\n\n",
            label="babel.localedata load",
            next_name="merge",
        )

    transform_source_text(context, "Lib/babel/core.py", patch_core)
    transform_source_text(context, "Lib/babel/localedata.py", patch_localedata)


LIBRARY_INTEGRATION = simple_library(
    name="babel",
    project_name="Babel",
    overlay_entries=["Lib/babel"],
    materialized_paths=[
        "Lib/babel/_staticpython_data.py",
    ],
    post_patch_hooks=[embed_babel_data],
)
