from __future__ import annotations

import base64

from libs import inline_verification_step, replace_text_once, simple_library, source_path, transform_source_text, write_source_text


def embed_babel_data(context) -> None:
    package_root = source_path(context, "Lib/babel")
    locale_data = {
        path.stem: base64.b64encode(path.read_bytes()).decode("ascii")
        for path in sorted((package_root / "locale-data").glob("*.dat"))
    }
    global_data = base64.b64encode((package_root / "global.dat").read_bytes()).decode("ascii")
    if not locale_data or "root" not in locale_data or "en_US" not in locale_data:
        raise RuntimeError("expected Babel locale-data files were not materialized")

    write_source_text(
        context,
        "Lib/babel/_staticpython_data.py",
        "# Generated by StaticPython; keeps Babel data files available after freezing.\n"
        "import base64\n\n"
        f"GLOBAL_DATA = {global_data!r}\n"
        f"LOCALE_DATA = {locale_data!r}\n\n"
        "def global_bytes() -> bytes:\n"
        "    return base64.b64decode(GLOBAL_DATA)\n\n"
        "def locale_bytes(name: str) -> bytes:\n"
        "    return base64.b64decode(LOCALE_DATA[name])\n",
    )

    def patch_core(text: str) -> str:
        text = text.replace(
            "from babel import localedata\n",
            "from babel import localedata\nfrom babel._staticpython_data import global_bytes as _staticpython_global_bytes\n",
            1,
        ) if "_staticpython_global_bytes" not in text else text
        return replace_text_once(
            text,
            "        dirname = os.path.join(os.path.dirname(__file__))\n"
            "        filename = os.path.join(dirname, 'global.dat')\n"
            "        if not os.path.isfile(filename):\n"
            "            _raise_no_data_error()\n"
            "        with open(filename, 'rb') as fileobj:\n"
            "            _global_data = pickle.load(fileobj)\n"
            "            assert _global_data is not None\n",
            "        _global_data = pickle.loads(_staticpython_global_bytes())\n"
            "        assert _global_data is not None\n",
            label="babel global data loader",
        )

    def patch_localedata(text: str) -> str:
        text = replace_text_once(
            text,
            "from typing import Any\n",
            "from typing import Any\n\nfrom babel._staticpython_data import LOCALE_DATA as _STATICPYTHON_LOCALE_DATA\nfrom babel._staticpython_data import locale_bytes as _staticpython_locale_bytes\n",
            label="babel localedata static data import",
        )
        text = replace_text_once(
            text,
            "    file_found = os.path.exists(resolve_locale_filename(name))\n"
            "    return True if file_found else bool(normalize_locale(name))\n",
            "    if name in _STATICPYTHON_LOCALE_DATA:\n"
            "        return True\n"
            "    file_found = os.path.exists(resolve_locale_filename(name))\n"
            "    return True if file_found else bool(normalize_locale(name))\n",
            label="babel locale exists loader",
        )
        text = replace_text_once(
            text,
            "    return [\n"
            "        stem\n"
            "        for stem, extension in (\n"
            "            os.path.splitext(filename) for filename in os.listdir(_dirname)\n"
            "        )\n"
            "        if extension == '.dat' and stem != 'root'\n"
            "    ]\n",
            "    if _STATICPYTHON_LOCALE_DATA:\n"
            "        return sorted(name for name in _STATICPYTHON_LOCALE_DATA if name != 'root')\n"
            "    return [\n"
            "        stem\n"
            "        for stem, extension in (\n"
            "            os.path.splitext(filename) for filename in os.listdir(_dirname)\n"
            "        )\n"
            "        if extension == '.dat' and stem != 'root'\n"
            "    ]\n",
            label="babel locale identifiers loader",
        )
        return replace_text_once(
            text,
            "            filename = resolve_locale_filename(name)\n"
            "            with open(filename, 'rb') as fileobj:\n"
            "                if name != 'root' and merge_inherited:\n"
            "                    merge(data, pickle.load(fileobj))\n"
            "                else:\n"
            "                    data = pickle.load(fileobj)\n",
            "            if name in _STATICPYTHON_LOCALE_DATA:\n"
            "                loaded = pickle.loads(_staticpython_locale_bytes(name))\n"
            "                if name != 'root' and merge_inherited:\n"
            "                    merge(data, loaded)\n"
            "                else:\n"
            "                    data = loaded\n"
            "            else:\n"
            "                filename = resolve_locale_filename(name)\n"
            "                with open(filename, 'rb') as fileobj:\n"
            "                    if name != 'root' and merge_inherited:\n"
            "                        merge(data, pickle.load(fileobj))\n"
            "                    else:\n"
            "                        data = pickle.load(fileobj)\n",
            label="babel locale data loader",
        )

    transform_source_text(context, "Lib/babel/core.py", patch_core)
    transform_source_text(context, "Lib/babel/localedata.py", patch_localedata)


LIBRARY_INTEGRATION = simple_library(
    name="babel",
    project_name="Babel",
    overlay_entries=["Lib/babel"],
    materialized_paths=[
        "Lib/babel/global.dat",
        "Lib/babel/locale-data/root.dat",
        "Lib/babel/locale-data/en.dat",
        "Lib/babel/locale-data/en_US.dat",
        "Lib/babel/_staticpython_data.py",
    ],
    verification_materialized_paths=[
        "Lib/babel/global.dat",
        "Lib/babel/locale-data/root.dat",
        "Lib/babel/locale-data/en.dat",
        "Lib/babel/locale-data/en_US.dat",
    ],
    post_patch_hooks=[embed_babel_data],
    verification_steps=[
        inline_verification_step(
            "babel-smoke",
            """
from datetime import datetime
from babel import Locale
from babel.dates import format_datetime
from babel.localedata import exists
from babel.numbers import format_currency

locale = Locale.parse("en_US")
formatted_datetime = format_datetime(datetime(2024, 1, 2, 3, 4, 5), locale="en_US")
formatted_currency = format_currency(1234.5, "USD", locale="en_US")

assert locale.display_name == "English (United States)"
assert "2024" in formatted_datetime
assert "3:04:05" in formatted_datetime
assert "$1,234.50" == formatted_currency
assert exists("root")
assert exists("en")
assert exists("en_US")
assert exists("fr_FR")
""",
        )
    ],
)
