from libs import simple_library, transform_source_text, write_source_text


def patch_plotly_sources(context):
    template_dir = context.source_root / "Lib" / "plotly" / "package_data" / "templates"
    templates = {
        template_path.stem: template_path.read_text(encoding="utf-8")
        for template_path in sorted(template_dir.glob("*.json"))
    }
    if not templates:
        raise RuntimeError("expected plotly package_data/templates JSON files were not materialized")

    write_source_text(
        context,
        "Lib/plotly/_staticpython_templates.py",
        "# Auto-generated by StaticPython's plotly integration.\n"
        "# Plotly normally loads these JSON files with pkgutil.get_data(),\n"
        "# which returns None for frozen-only modules.\n"
        f"TEMPLATES = {templates!r}\n",
    )

    def patch_init(text):
        old = '__version__ = importlib.metadata.version("plotly")'
        new = (
            'try:\n'
            '    __version__ = importlib.metadata.version("plotly")\n'
            'except importlib.metadata.PackageNotFoundError:\n'
            '    __version__ = "0+staticpython"'
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly version metadata lookup was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/__init__.py", patch_init)

    def patch_templates(text):
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_templates import TEMPLATES as _STATICPYTHON_TEMPLATES\n"
            "except Exception:\n"
            "    _STATICPYTHON_TEMPLATES = {}\n\n"
        )
        if "_STATICPYTHON_TEMPLATES" not in text:
            text = text.replace("import json\n", "import json\n" + import_guard, 1)

        old = '                    template_str = pkgutil.get_data("plotly", path).decode("utf-8")'
        new = (
            '                    template_data = pkgutil.get_data("plotly", path)\n'
            '                    if template_data is None:\n'
            '                        template_str = _STATICPYTHON_TEMPLATES.get(template_name)\n'
            '                        if template_str is None:\n'
            '                            raise FileNotFoundError(path)\n'
            '                    else:\n'
            '                        template_str = template_data.decode("utf-8")'
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly template pkgutil.get_data lookup was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/io/_templates.py", patch_templates)


LIBRARY_INTEGRATION = simple_library(
    name="plotly",
    source_mapping={
        "plotly": "Lib/plotly",
        "_plotly_utils": "Lib/_plotly_utils",
    },
    post_patch_hooks=[patch_plotly_sources],
)
