import json
import re

from libs import (
    ensure_text_after,
    replace_function_block_once,
    replace_regex_once,
    simple_library,
    transform_first_existing_source_text,
    transform_source_text,
    write_source_text,
)


def patch_plotly_sources(context):
    package_data_dir = context.source_root / "Lib" / "plotly" / "package_data"
    if not package_data_dir.exists():
        # Very early plotly releases predate package_data/_plotly_utils/validator-era layouts.
        write_source_text(
            context,
            "Lib/plotly/_staticpython_package_data.py",
            "# Auto-generated by StaticPython's plotly integration.\n"
            "# Early plotly releases do not ship package_data resources.\n"
            "PLOTLY_MIN_JS = None\n"
            "DATASETS = {}\n",
        )
        return
    template_dir = context.source_root / "Lib" / "plotly" / "package_data" / "templates"
    templates = {
        template_path.stem: template_path.read_text(encoding="utf-8")
        for template_path in sorted(template_dir.glob("*.json"))
    }
    plotly_min_js = (package_data_dir / "plotly.min.js").read_text(encoding="utf-8")
    dataset_dir = package_data_dir / "datasets"
    datasets = {
        dataset_path.name: dataset_path.read_bytes()
        for dataset_path in sorted(dataset_dir.glob("*.gz"))
    }
    validators_path = context.source_root / "Lib" / "plotly" / "validators" / "_validators.json"
    validators = (
        json.loads(validators_path.read_text(encoding="utf-8"))
        if validators_path.exists()
        else None
    )
    if not plotly_min_js:
        raise RuntimeError("expected plotly package_data/plotly.min.js was not materialized")
    has_template_support = (context.source_root / "Lib" / "plotly" / "io" / "_templates.py").exists()
    has_dataset_support = (context.source_root / "Lib" / "plotly" / "data" / "__init__.py").exists()
    legacy_dataset_dir = context.source_root / "Lib" / "plotly" / "data"
    if not datasets and legacy_dataset_dir.exists():
        datasets = {
            dataset_path.name: dataset_path.read_bytes()
            for dataset_path in sorted(legacy_dataset_dir.glob("*.gz"))
        }
    if has_template_support and not templates:
        raise RuntimeError("expected plotly package_data/templates JSON files were not materialized")
    # Some early 4.0.0 pre-releases shipped plotly.data helpers without bundling
    # the backing .gz files in the sdist. Treat that era as an allowed no-data
    # layout and let the patched runtime raise only if those helpers are actually used.
    allow_missing_datasets = has_dataset_support and not datasets

    write_source_text(
        context,
        "Lib/plotly/_staticpython_templates.py",
        "# Auto-generated by StaticPython's plotly integration.\n"
        "# Plotly normally loads these JSON files with pkgutil.get_data(),\n"
        "# which returns None for frozen-only modules.\n"
        f"TEMPLATES = {templates!r}\n",
    )
    if validators is not None:
        write_source_text(
            context,
            "Lib/plotly/_staticpython_validators.py",
            "# Auto-generated by StaticPython's plotly integration.\n"
            "# Plotly normally loads validator metadata from validators/_validators.json.\n"
            f"VALIDATORS = {validators!r}\n",
        )
    write_source_text(
        context,
        "Lib/plotly/_staticpython_package_data.py",
        "# Auto-generated by StaticPython's plotly integration.\n"
        "# Plotly normally loads these package_data resources from files.\n"
        f"PLOTLY_MIN_JS = {plotly_min_js!r}\n"
        f"DATASETS = {datasets!r}\n",
    )
    package_data = {
        path.relative_to(package_data_dir).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(package_data_dir.rglob("*"))
        if path.is_file()
        and path.suffix.lower() in {".js", ".json"}
        and path.name != "plotly.min.js"
    }
    if package_data:
        write_source_text(
            context,
            "Lib/plotly/_staticpython_package_data_extras.py",
            "# Auto-generated by StaticPython's plotly integration.\n"
            "# Keeps smaller package_data text resources available after freezing.\n"
            f"PLOTLY_PACKAGE_DATA = {package_data!r}\n",
        )

    def patch_version_metadata(text: str) -> str:
        if "PackageNotFoundError" in text and "__version__" in text:
            return text
        if '__version__ = importlib.metadata.version("plotly")' in text:
            return text.replace(
                '__version__ = importlib.metadata.version("plotly")',
                "try:\n"
                '    __version__ = importlib.metadata.version("plotly")\n'
                "except importlib.metadata.PackageNotFoundError:\n"
                '    __version__ = "0+staticpython"',
                1,
            )
        import_match = re.search(r"(?m)^from importlib\.metadata import (?P<names>.+)\n", text)
        version_match = re.search(r'(?m)^__version__ = version\((?P<arg>.+?)\)\n', text)
        if import_match is None or version_match is None or "version" not in import_match.group("names"):
            if "__version__" in text and "version(" in text and "PackageNotFoundError" not in text:
                raise RuntimeError("plotly version metadata anchor not found")
            return text
        imported_names = import_match.group("names")
        replacement_names = imported_names if "PackageNotFoundError" in imported_names else f"PackageNotFoundError, {imported_names}"
        updated = text[: import_match.start()] + f"from importlib.metadata import {replacement_names}\n" + text[import_match.end() :]
        updated, count = re.subn(
            r'(?m)^__version__ = version\((?P<arg>.+?)\)\n',
            'try:\n    __version__ = version(\\g<arg>)\nexcept PackageNotFoundError:\n    __version__ = "0+staticpython"\n',
            updated,
            count=1,
        )
        if count != 1:
            raise RuntimeError("plotly version metadata replacement failed")
        return updated

    transform_first_existing_source_text(
        context,
        [
            "Lib/plotly/__init__.py",
            "Lib/plotly/_version.py",
            "Lib/plotly/version.py",
        ],
        patch_version_metadata,
        allow_all_missing=True,
    )

    def patch_templates(text):
        if not text:
            return text
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_templates import TEMPLATES as _STATICPYTHON_TEMPLATES\n"
            "except Exception:\n"
            "    _STATICPYTHON_TEMPLATES = {}\n\n"
        )
        if "_STATICPYTHON_TEMPLATES" not in text:
            if "import json\n" in text:
                text = text.replace("import json\n", "import json\n" + import_guard, 1)
            elif "pkgutil.get_data" in text:
                raise RuntimeError("plotly template static import anchor not found")

        if "template_basename = os.path.splitext(os.path.basename(path))[0]" in text:
            return text
        return replace_regex_once(
            text,
            r"""(?m)^(?P<indent>\s*)template_str = pkgutil\.get_data\((['"])plotly\2, path\)\.decode\((['"])utf-8\3\)\s*$""",
            (
                "\\g<indent>template_data = pkgutil.get_data(\"plotly\", path)\n"
                "\\g<indent>if template_data is None:\n"
                "\\g<indent>    template_basename = os.path.splitext(os.path.basename(path))[0]\n"
                "\\g<indent>    template_str = _STATICPYTHON_TEMPLATES.get(template_basename)\n"
                "\\g<indent>    if template_str is None:\n"
                "\\g<indent>        raise FileNotFoundError(path)\n"
                "\\g<indent>else:\n"
                "\\g<indent>    template_str = template_data.decode(\"utf-8\")"
            ),
            label="plotly template pkgutil.get_data fallback",
        )

    transform_source_text(context, "Lib/plotly/io/_templates.py", patch_templates, allow_missing=True)

    def patch_offline(text):
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_package_data import PLOTLY_MIN_JS as _STATICPYTHON_PLOTLY_MIN_JS\n"
            "except Exception:\n"
            "    _STATICPYTHON_PLOTLY_MIN_JS = None\n\n"
        )
        if "_STATICPYTHON_PLOTLY_MIN_JS" not in text:
            if "import pkgutil\n" in text:
                text = text.replace("import pkgutil\n", "import pkgutil\n" + import_guard, 1)
            elif "from pkg_resources import resource_string\n" in text:
                text = text.replace(
                    "from pkg_resources import resource_string\n",
                    "from pkg_resources import resource_string\n" + import_guard,
                    1,
                )
            else:
                if "plotly.min.js" in text:
                    raise RuntimeError("plotly.min.js import anchor not found")
                return text

        modern_old = (
            "    path = os.path.join('package_data', 'plotly.min.js')\n"
            "    plotlyjs = pkgutil.get_data('plotly', path).decode('utf-8')\n"
            "    return plotlyjs\n"
        )
        old = (
            "    path = os.path.join(\"package_data\", \"plotly.min.js\")\n"
            "    plotlyjs = pkgutil.get_data(\"plotly\", path).decode(\"utf-8\")\n"
            "    return plotlyjs\n"
        )
        legacy_old = (
            "    path = os.path.join('package_data', 'plotly.min.js')\n"
            "    plotlyjs = resource_string('plotly', path).decode('utf-8')\n"
            "    return plotlyjs\n"
        )
        legacy_old_double = (
            "    path = os.path.join(\"package_data\", \"plotly.min.js\")\n"
            "    plotlyjs = resource_string('plotly', path).decode('utf-8')\n"
            "    return plotlyjs\n"
        )
        new = (
            "    path = os.path.join(\"package_data\", \"plotly.min.js\")\n"
            "    try:\n"
            "        plotlyjs_data = pkgutil.get_data(\"plotly\", path)\n"
            "    except (AssertionError, FileNotFoundError):\n"
            "        plotlyjs_data = None\n"
            "    except Exception:\n"
            "        try:\n"
            "            plotlyjs_data = resource_string(\"plotly\", path)\n"
            "        except Exception:\n"
            "            plotlyjs_data = None\n"
            "    if plotlyjs_data is not None:\n"
            "        return plotlyjs_data.decode(\"utf-8\")\n"
            "    if _STATICPYTHON_PLOTLY_MIN_JS is not None:\n"
            "        return _STATICPYTHON_PLOTLY_MIN_JS\n"
            "    raise FileNotFoundError(path)\n"
        )
        if new in text:
            return text
        for candidate in (modern_old, old, legacy_old, legacy_old_double):
            if candidate in text:
                return text.replace(candidate, new, 1)
        raise RuntimeError("expected plotly.min.js loader was not found")

    transform_source_text(context, "Lib/plotly/offline/offline.py", patch_offline)

    def patch_graph_reference(text: str) -> str:
        if "_STATICPYTHON_PLOTLY_PACKAGE_DATA" not in text:
            import_guard = (
                "try:\n"
                "    from plotly._staticpython_package_data_extras import PLOTLY_PACKAGE_DATA as _STATICPYTHON_PLOTLY_PACKAGE_DATA\n"
                "except Exception:\n"
                "    _STATICPYTHON_PLOTLY_PACKAGE_DATA = {}\n\n"
            )
            if "import pkgutil\n" in text:
                text = ensure_text_after(
                    text,
                    "import pkgutil\n",
                    import_guard,
                    label="plotly graph_reference static package data import",
                )
            elif "from pkg_resources import resource_string\n" in text:
                text = text.replace("from pkg_resources import resource_string\n", "import pkgutil\n", 1)
                text = ensure_text_after(
                    text,
                    "import pkgutil\n",
                    import_guard,
                    label="plotly graph_reference static package data import",
                )
            else:
                if "pkgutil.get_data" in text or "resource_string(" in text:
                    raise RuntimeError("plotly graph_reference static import anchor not found")
                return text

        modern_old = "    s = pkgutil.get_data('plotly', path).decode('utf-8')\n"
        legacy_old = "    s = resource_string('plotly', path).decode('utf-8')\n"
        replacement = (
            "    schema_data = pkgutil.get_data('plotly', path)\n"
            "    if schema_data is not None:\n"
            "        s = schema_data.decode('utf-8')\n"
            "    else:\n"
            "        s = _STATICPYTHON_PLOTLY_PACKAGE_DATA[path]\n"
        )
        if replacement in text:
            return text
        if modern_old in text:
            return text.replace(modern_old, replacement, 1)
        if legacy_old in text:
            return text.replace(legacy_old, replacement, 1)
        if "pkgutil.get_data" in text or "resource_string(" in text:
            raise RuntimeError("expected plotly graph_reference package-data loader was not found")
        return text

    transform_first_existing_source_text(
        context,
        ["Lib/plotly/graph_reference.py"],
        patch_graph_reference,
        allow_all_missing=True,
    )

    def patch_graph_widget(text: str) -> str:
        if "_STATICPYTHON_PLOTLY_PACKAGE_DATA" not in text:
            import_guard = (
                "try:\n"
                "    from plotly._staticpython_package_data_extras import PLOTLY_PACKAGE_DATA as _STATICPYTHON_PLOTLY_PACKAGE_DATA\n"
                "except Exception:\n"
                "    _STATICPYTHON_PLOTLY_PACKAGE_DATA = {}\n\n"
            )
            if "import pkgutil\n" in text:
                text = ensure_text_after(
                    text,
                    "import pkgutil\n",
                    import_guard,
                    label="plotly graph_widget static package data import",
                )
            elif "from pkg_resources import resource_string\n" in text:
                text = text.replace("from pkg_resources import resource_string\n", "import pkgutil\n", 1)
                text = ensure_text_after(
                    text,
                    "import pkgutil\n",
                    import_guard,
                    label="plotly graph_widget static package data import",
                )
            else:
                if "graphWidget.js" in text or "pkgutil.get_data" in text or "resource_string(" in text:
                    raise RuntimeError("plotly graph widget static import anchor not found")
                return text

        modern_old = (
            "js_widget_code = pkgutil.get_data('plotly',\n"
            "                                  'package_data/graphWidget.js'\n"
            "                                  ).decode('utf-8')\n"
        )
        legacy_old = (
            "js_widget_code = resource_string('plotly',\n"
            "                                 'package_data/graphWidget.js').decode('utf-8')\n"
        )
        replacement = (
            "js_widget_data = pkgutil.get_data('plotly', 'package_data/graphWidget.js')\n"
            "if js_widget_data is not None:\n"
            "    js_widget_code = js_widget_data.decode('utf-8')\n"
            "else:\n"
            "    js_widget_code = _STATICPYTHON_PLOTLY_PACKAGE_DATA['package_data/graphWidget.js']\n"
        )
        if replacement in text:
            return text
        if modern_old in text:
            return text.replace(modern_old, replacement, 1)
        if legacy_old in text:
            return text.replace(legacy_old, replacement, 1)
        if "graphWidget.js" in text or "pkgutil.get_data" in text or "resource_string(" in text:
            raise RuntimeError("expected plotly graph widget package-data loader was not found")
        return text

    transform_first_existing_source_text(
        context,
        ["Lib/plotly/widgets/graph_widget.py"],
        patch_graph_widget,
        allow_all_missing=True,
    )

    def patch_data(text):
        if not text:
            return text
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_package_data import DATASETS as _STATICPYTHON_DATASETS\n"
            "except Exception:\n"
            "    _STATICPYTHON_DATASETS = {}\n\n"
        )
        if "_STATICPYTHON_DATASETS" not in text:
            if text.startswith('"""'):
                end = text.find('"""\n', 3)
                if end != -1:
                    insert_at = end + 4
                    text = text[:insert_at] + "\nimport gzip\nimport io\nimport json\nimport os\n\n" + import_guard + text[insert_at:]
            elif text.startswith("'''"):
                end = text.find("'''\n", 3)
                if end != -1:
                    insert_at = end + 4
                    text = text[:insert_at] + "\nimport gzip\nimport io\nimport json\nimport os\n\n" + import_guard + text[insert_at:]
            elif "import os\n" in text:
                text = text.replace("import os\n", "import gzip\nimport io\nimport json\nimport os\n" + import_guard, 1)
            else:
                text = "import gzip\nimport io\nimport json\nimport os\n\n" + import_guard + text

        if "def _get_dataset(d):" in text and "dataset_candidates = [" not in text:
            text = replace_function_block_once(
                text,
                "_get_dataset",
                'def _get_dataset(d):\n'
                '    import pandas\n\n'
                '    dataset_name = d + ".csv.gz"\n'
                '    dataset_bytes = _STATICPYTHON_DATASETS.get(dataset_name)\n'
                '    if dataset_bytes is not None:\n'
                '        return pandas.read_csv(io.BytesIO(gzip.decompress(dataset_bytes)))\n\n'
                '    dataset_candidates = [\n'
                '        os.path.join(\n'
                '            os.path.dirname(os.path.dirname(__file__)),\n'
                '            "package_data",\n'
                '            "datasets",\n'
                '            dataset_name,\n'
                '        ),\n'
                '        os.path.join(os.path.dirname(__file__), dataset_name),\n'
                '    ]\n'
                '    for filepath in dataset_candidates:\n'
                '        if os.path.exists(filepath):\n'
                '            return pandas.read_csv(filepath)\n'
                '    raise FileNotFoundError(dataset_name)\n\n',
                label="plotly dataset loader fallback",
                next_name=None,
            )

        if "def election_geojson():" in text and 'geojson_bytes = _STATICPYTHON_DATASETS.get("election.geojson.gz")' not in text:
            text = replace_function_block_once(
                text,
                "election_geojson",
                'def election_geojson():\n'
                '    """\n'
                'Each feature represents an electoral district in the 2013 Montreal mayoral election.\n\n'
                'Returns:\n'
                '    A GeoJSON-formatted `dict`.\n'
                '    """\n'
                '    geojson_name = "election.geojson.gz"\n'
                '    geojson_bytes = _STATICPYTHON_DATASETS.get(geojson_name)\n'
                '    if geojson_bytes is not None:\n'
                '        with gzip.GzipFile(fileobj=io.BytesIO(geojson_bytes), mode="r") as f:\n'
                '            return json.loads(f.read().decode("utf-8"))\n\n'
                '    dataset_candidates = [\n'
                '        os.path.join(\n'
                '            os.path.dirname(os.path.dirname(__file__)),\n'
                '            "package_data",\n'
                '            "datasets",\n'
                '            geojson_name,\n'
                '        ),\n'
                '        os.path.join(os.path.dirname(__file__), geojson_name),\n'
                '    ]\n'
                '    for filepath in dataset_candidates:\n'
                '        if os.path.exists(filepath):\n'
                '            with gzip.GzipFile(filepath, "r") as f:\n'
                '                return json.loads(f.read().decode("utf-8"))\n'
                '    raise FileNotFoundError(geojson_name)\n\n',
                label="plotly election geojson loader fallback",
                next_name=None,
            )

        return text

    transform_source_text(context, "Lib/plotly/data/__init__.py", patch_data, allow_missing=True)

    def patch_validator_cache(text):
        if "_validators.json" not in text:
            return text
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_validators import VALIDATORS as _STATICPYTHON_VALIDATORS\n"
            "except Exception:\n"
            "    _STATICPYTHON_VALIDATORS = None\n\n"
        )
        if "_STATICPYTHON_VALIDATORS" not in text:
            text = text.replace("import os.path as opath\n", "import os.path as opath\n" + import_guard, 1)

        old = (
            "        if ValidatorCache._json_cache is None:\n"
            "            # Load the JSON validator params from the file\n"
            "            validator_json_path = opath.join(\n"
            "                opath.dirname(__file__), \"validators\", \"_validators.json\"\n"
            "            )\n"
            "            if not opath.exists(validator_json_path):\n"
            "                raise FileNotFoundError(\n"
            "                    f\"Validator JSON file not found: {validator_json_path}\"\n"
            "                )\n"
            "            with open(validator_json_path, \"r\") as f:\n"
            "                ValidatorCache._json_cache = json.load(f)\n"
        )
        new = (
            "        if ValidatorCache._json_cache is None:\n"
            "            if _STATICPYTHON_VALIDATORS is not None:\n"
            "                ValidatorCache._json_cache = _STATICPYTHON_VALIDATORS\n"
            "            else:\n"
            "                # Load the JSON validator params from the file\n"
            "                validator_json_path = opath.join(\n"
            "                    opath.dirname(__file__), \"validators\", \"_validators.json\"\n"
            "                )\n"
            "                if not opath.exists(validator_json_path):\n"
            "                    raise FileNotFoundError(\n"
            "                        f\"Validator JSON file not found: {validator_json_path}\"\n"
            "                    )\n"
            "                with open(validator_json_path, \"r\") as f:\n"
            "                    ValidatorCache._json_cache = json.load(f)\n"
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly validator JSON loader was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/validator_cache.py", patch_validator_cache, allow_missing=True)

    def patch_legacy_tools(text: str) -> str:
        if "_STATICPYTHON_PLOTLY_MIN_JS" in text:
            return text
        if "get_embed('plotly')" not in text:
            return text
        if "from plotly._staticpython_package_data import PLOTLY_MIN_JS as _STATICPYTHON_PLOTLY_MIN_JS" not in text:
            text = text.replace(
                "from plotly import exceptions, optional_imports\n",
                "from plotly import exceptions, optional_imports\n"
                "try:\n"
                "    from plotly._staticpython_package_data import PLOTLY_MIN_JS as _STATICPYTHON_PLOTLY_MIN_JS\n"
                "except Exception:\n"
                "    _STATICPYTHON_PLOTLY_MIN_JS = None\n",
                1,
            )
        updated, count = re.subn(
            r"""(?ms)^(\s*)path = os\.path\.join\('package_data', 'plotly\.min\.js'\)\n\s*plotlyjs = resource_string\('plotly', path\)\.decode\('utf-8'\)\n\s*return plotlyjs\n""",
            (
                "    path = os.path.join('package_data', 'plotly.min.js')\n"
                "    try:\n"
                "        plotlyjs_data = resource_string('plotly', path)\n"
                "    except Exception:\n"
                "        plotlyjs_data = None\n"
                "    if plotlyjs_data is not None:\n"
                "        return plotlyjs_data.decode('utf-8')\n"
                "    if _STATICPYTHON_PLOTLY_MIN_JS is not None:\n"
                "        return _STATICPYTHON_PLOTLY_MIN_JS\n"
                "    raise FileNotFoundError(path)\n"
            ),
            text,
            count=1,
        )
        if count == 1:
            return updated
        if "resource_string('plotly', path)" in text or "plotly.min.js" in text:
            raise RuntimeError("expected legacy plotly.min.js loader was not found")
        return text

    transform_first_existing_source_text(
        context,
        [
            "Lib/plotly/tools.py",
            "Lib/plotly/offline/offline.py",
        ],
        patch_legacy_tools,
        allow_all_missing=True,
    )
LIBRARY_INTEGRATION = simple_library(
    name="plotly",
    source_mapping={
        "plotly": "Lib/plotly",
        "?_plotly_utils": "Lib/_plotly_utils",
    },
    materialized_paths=[
        "Lib/plotly/_staticpython_package_data.py",
    ],
    post_patch_hooks=[patch_plotly_sources],
)
