import json

from libs import simple_library, transform_source_text, write_source_text


def patch_plotly_sources(context):
    package_data_dir = context.source_root / "Lib" / "plotly" / "package_data"
    template_dir = context.source_root / "Lib" / "plotly" / "package_data" / "templates"
    templates = {
        template_path.stem: template_path.read_text(encoding="utf-8")
        for template_path in sorted(template_dir.glob("*.json"))
    }
    plotly_min_js = (package_data_dir / "plotly.min.js").read_text(encoding="utf-8")
    dataset_dir = package_data_dir / "datasets"
    datasets = {
        dataset_path.name: dataset_path.read_bytes()
        for dataset_path in sorted(dataset_dir.glob("*.gz"))
    }
    validators_path = context.source_root / "Lib" / "plotly" / "validators" / "_validators.json"
    validators = (
        json.loads(validators_path.read_text(encoding="utf-8"))
        if validators_path.exists()
        else None
    )
    if not templates:
        raise RuntimeError("expected plotly package_data/templates JSON files were not materialized")
    if not plotly_min_js:
        raise RuntimeError("expected plotly package_data/plotly.min.js was not materialized")
    if not datasets:
        raise RuntimeError("expected plotly package_data/datasets files were not materialized")

    write_source_text(
        context,
        "Lib/plotly/_staticpython_templates.py",
        "# Auto-generated by StaticPython's plotly integration.\n"
        "# Plotly normally loads these JSON files with pkgutil.get_data(),\n"
        "# which returns None for frozen-only modules.\n"
        f"TEMPLATES = {templates!r}\n",
    )
    if validators is not None:
        write_source_text(
            context,
            "Lib/plotly/_staticpython_validators.py",
            "# Auto-generated by StaticPython's plotly integration.\n"
            "# Plotly normally loads validator metadata from validators/_validators.json.\n"
            f"VALIDATORS = {validators!r}\n",
        )
    write_source_text(
        context,
        "Lib/plotly/_staticpython_package_data.py",
        "# Auto-generated by StaticPython's plotly integration.\n"
        "# Plotly normally loads these package_data resources from files.\n"
        f"PLOTLY_MIN_JS = {plotly_min_js!r}\n"
        f"DATASETS = {datasets!r}\n",
    )

    def patch_init(text):
        old = '__version__ = importlib.metadata.version("plotly")'
        new = (
            'try:\n'
            '    __version__ = importlib.metadata.version("plotly")\n'
            'except importlib.metadata.PackageNotFoundError:\n'
            '    __version__ = "0+staticpython"'
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly version metadata lookup was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/__init__.py", patch_init)

    def patch_templates(text):
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_templates import TEMPLATES as _STATICPYTHON_TEMPLATES\n"
            "except Exception:\n"
            "    _STATICPYTHON_TEMPLATES = {}\n\n"
        )
        if "_STATICPYTHON_TEMPLATES" not in text:
            text = text.replace("import json\n", "import json\n" + import_guard, 1)

        old = '                    template_str = pkgutil.get_data("plotly", path).decode("utf-8")'
        new = (
            '                    template_data = pkgutil.get_data("plotly", path)\n'
            '                    if template_data is None:\n'
            '                        template_str = _STATICPYTHON_TEMPLATES.get(template_name)\n'
            '                        if template_str is None:\n'
            '                            raise FileNotFoundError(path)\n'
            '                    else:\n'
            '                        template_str = template_data.decode("utf-8")'
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly template pkgutil.get_data lookup was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/io/_templates.py", patch_templates)

    def patch_offline(text):
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_package_data import PLOTLY_MIN_JS as _STATICPYTHON_PLOTLY_MIN_JS\n"
            "except Exception:\n"
            "    _STATICPYTHON_PLOTLY_MIN_JS = None\n\n"
        )
        if "_STATICPYTHON_PLOTLY_MIN_JS" not in text:
            text = text.replace("import pkgutil\n\n", "import pkgutil\n\n" + import_guard, 1)

        old = (
            "    path = os.path.join(\"package_data\", \"plotly.min.js\")\n"
            "    plotlyjs = pkgutil.get_data(\"plotly\", path).decode(\"utf-8\")\n"
            "    return plotlyjs\n"
        )
        new = (
            "    path = os.path.join(\"package_data\", \"plotly.min.js\")\n"
            "    try:\n"
            "        plotlyjs_data = pkgutil.get_data(\"plotly\", path)\n"
            "    except (AssertionError, FileNotFoundError):\n"
            "        plotlyjs_data = None\n"
            "    if plotlyjs_data is not None:\n"
            "        return plotlyjs_data.decode(\"utf-8\")\n"
            "    if _STATICPYTHON_PLOTLY_MIN_JS is not None:\n"
            "        return _STATICPYTHON_PLOTLY_MIN_JS\n"
            "    raise FileNotFoundError(path)\n"
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly.min.js loader was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/offline/offline.py", patch_offline)

    def patch_data(text):
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_package_data import DATASETS as _STATICPYTHON_DATASETS\n"
            "except Exception:\n"
            "    _STATICPYTHON_DATASETS = {}\n\n"
        )
        if "_STATICPYTHON_DATASETS" not in text:
            text = text.replace(
                "import os\nfrom importlib import import_module\n\n",
                "import gzip\nimport io\nimport os\nfrom importlib import import_module\n\n" + import_guard,
                1,
            )

        old_geojson = (
            "    path = os.path.join(\n"
            "        os.path.dirname(os.path.dirname(__file__)),\n"
            "        \"package_data\",\n"
            "        \"datasets\",\n"
            "        \"election.geojson.gz\",\n"
            "    )\n"
            "    with gzip.GzipFile(path, \"r\") as f:\n"
            "        result = json.loads(f.read().decode(\"utf-8\"))\n"
            "    return result\n"
        )
        new_geojson = (
            "    geojson_bytes = _STATICPYTHON_DATASETS.get(\"election.geojson.gz\")\n"
            "    if geojson_bytes is not None:\n"
            "        with gzip.GzipFile(fileobj=io.BytesIO(geojson_bytes), mode=\"r\") as f:\n"
            "            return json.loads(f.read().decode(\"utf-8\"))\n"
            "    path = os.path.join(\n"
            "        os.path.dirname(os.path.dirname(__file__)),\n"
            "        \"package_data\",\n"
            "        \"datasets\",\n"
            "        \"election.geojson.gz\",\n"
            "    )\n"
            "    with gzip.GzipFile(path, \"r\") as f:\n"
            "        result = json.loads(f.read().decode(\"utf-8\"))\n"
            "    return result\n"
        )
        if new_geojson not in text:
            if old_geojson not in text:
                raise RuntimeError("expected plotly election.geojson loader was not found")
            text = text.replace(old_geojson, new_geojson, 1)

        old_dataset = (
            "    filepath = os.path.join(\n"
            "        os.path.dirname(os.path.dirname(__file__)),\n"
            "        \"package_data\",\n"
            "        \"datasets\",\n"
            "        d + \".csv.gz\",\n"
            "    )\n"
        )
        new_dataset = (
            "    dataset_name = d + \".csv.gz\"\n"
            "    dataset_bytes = _STATICPYTHON_DATASETS.get(dataset_name)\n"
            "    if dataset_bytes is None:\n"
            "        filepath = os.path.join(\n"
            "            os.path.dirname(os.path.dirname(__file__)),\n"
            "            \"package_data\",\n"
            "            \"datasets\",\n"
            "            dataset_name,\n"
            "        )\n"
            "    else:\n"
            "        filepath = io.BytesIO(gzip.decompress(dataset_bytes))\n"
        )
        if new_dataset not in text:
            if old_dataset not in text:
                raise RuntimeError("expected plotly dataset filepath builder was not found")
            text = text.replace(old_dataset, new_dataset, 1)

        return text

    transform_source_text(context, "Lib/plotly/data/__init__.py", patch_data)

    def patch_validator_cache(text):
        if "_validators.json" not in text:
            return text
        import_guard = (
            "try:\n"
            "    from plotly._staticpython_validators import VALIDATORS as _STATICPYTHON_VALIDATORS\n"
            "except Exception:\n"
            "    _STATICPYTHON_VALIDATORS = None\n\n"
        )
        if "_STATICPYTHON_VALIDATORS" not in text:
            text = text.replace("import os.path as opath\n", "import os.path as opath\n" + import_guard, 1)

        old = (
            "        if ValidatorCache._json_cache is None:\n"
            "            # Load the JSON validator params from the file\n"
            "            validator_json_path = opath.join(\n"
            "                opath.dirname(__file__), \"validators\", \"_validators.json\"\n"
            "            )\n"
            "            if not opath.exists(validator_json_path):\n"
            "                raise FileNotFoundError(\n"
            "                    f\"Validator JSON file not found: {validator_json_path}\"\n"
            "                )\n"
            "            with open(validator_json_path, \"r\") as f:\n"
            "                ValidatorCache._json_cache = json.load(f)\n"
        )
        new = (
            "        if ValidatorCache._json_cache is None:\n"
            "            if _STATICPYTHON_VALIDATORS is not None:\n"
            "                ValidatorCache._json_cache = _STATICPYTHON_VALIDATORS\n"
            "            else:\n"
            "                # Load the JSON validator params from the file\n"
            "                validator_json_path = opath.join(\n"
            "                    opath.dirname(__file__), \"validators\", \"_validators.json\"\n"
            "                )\n"
            "                if not opath.exists(validator_json_path):\n"
            "                    raise FileNotFoundError(\n"
            "                        f\"Validator JSON file not found: {validator_json_path}\"\n"
            "                    )\n"
            "                with open(validator_json_path, \"r\") as f:\n"
            "                    ValidatorCache._json_cache = json.load(f)\n"
        )
        if new in text:
            return text
        if old not in text:
            raise RuntimeError("expected plotly validator JSON loader was not found")
        return text.replace(old, new, 1)

    transform_source_text(context, "Lib/plotly/validator_cache.py", patch_validator_cache)


LIBRARY_INTEGRATION = simple_library(
    name="plotly",
    source_mapping={
        "plotly": "Lib/plotly",
        "_plotly_utils": "Lib/_plotly_utils",
    },
    materialized_paths=[
        "Lib/plotly/_staticpython_templates.py",
        "Lib/plotly/_staticpython_package_data.py",
    ],
    post_patch_hooks=[patch_plotly_sources],
)
