/*
 * Copyright 2026 xqy2006
 * SPDX-License-Identifier: Apache-2.0
 *
 * StaticPythonPackV1 is intentionally scoped to one CPython minor ABI.
 * A pack built for cp313 must never be loaded into cp312 or cp314.
 */
#ifndef STATICPYTHON_PACK_H
#define STATICPYTHON_PACK_H

#include "Python.h"

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define STATICPYTHON_PACK_ABI_VERSION 1u
#define STATICPYTHON_RESOURCE_RAW 0u
#define STATICPYTHON_RESOURCE_ZLIB 1u

typedef struct StaticPythonFrozenModuleV1 {
    const char *name;
    const unsigned char *code;
    int size;
    int is_package;
#if PY_VERSION_HEX < 0x030D0000
    PyObject *(*get_code)(void);
#endif
} StaticPythonFrozenModuleV1;

typedef struct StaticPythonBuiltinModuleV1 {
    const char *name;
    PyObject *(*initfunc)(void);
} StaticPythonBuiltinModuleV1;

typedef struct StaticPythonResourceV1 {
    /* Slash-separated, UTF-8 virtual path. */
    const char *path;

    /*
     * Frozen-Python payload location.  Set module_name/blob_id for the
     * legacy zlib+b85 resource shards generated by StaticPython.
     */
    const char *module_name;
    const char *blob_id;

    /*
     * Native payload location.  A library pack may instead point at linked
     * bytes.  data_size is the linked size and size is the decoded size.
     */
    const unsigned char *data;
    size_t data_size;
    size_t size;
    uint32_t compression;
} StaticPythonResourceV1;

typedef int (*StaticPythonPackHookV1)(void);

typedef struct StaticPythonPackV1 {
    uint32_t struct_size;
    uint32_t abi_version;
    const char *name;
    const char *version;
    const char *cpython_abi;

    const StaticPythonFrozenModuleV1 *frozen_modules;
    size_t frozen_module_count;
    const StaticPythonBuiltinModuleV1 *builtin_modules;
    size_t builtin_module_count;
    const StaticPythonResourceV1 *resources;
    size_t resource_count;

    const char *const *dependencies;
    size_t dependency_count;
    const char *const *link_libraries;
    size_t link_library_count;
    const char *const *system_libraries;
    size_t system_library_count;
    StaticPythonPackHookV1 before_initialize;
} StaticPythonPackV1;

/*
 * Register all selected packs before Py_InitializeFromConfig().  The call is
 * transactional: validation failures leave CPython's frozen and builtin
 * tables untouched.  The pack descriptors and their pointed-to data must
 * remain alive for the lifetime of the process.
 */
int StaticPython_RegisterPacks(
    const StaticPythonPackV1 *const *packs,
    size_t pack_count
);

const char *StaticPython_LastError(void);
const char *StaticPython_RuntimeABI(void);

/* Defined by the runtime-sdk resource index generated during the build. */
extern const StaticPythonPackV1 StaticPython_BaseResourcePackV1;

#ifdef __cplusplus
}
#endif

#endif /* STATICPYTHON_PACK_H */
