from libs import inline_verification_step, LibraryHookContext, simple_library


def embed_cacert_pem(context: LibraryHookContext) -> None:
    certifi_dir = context.source_root / "Lib" / "certifi"
    cacert_path = certifi_dir / "cacert.pem"
    core_path = certifi_dir / "core.py"
    cacert_pem = cacert_path.read_text(encoding="ascii")
    embedded = repr(cacert_pem)
    core_path.write_text(
        f'''"""
certifi.py
~~~~~~~~~~

Single-file friendly certifi core generated by StaticPython.
"""

import hashlib
import os
import tempfile


_CACERT_PEM = {embedded}
_CACERT_PATH = None


def where() -> str:
    global _CACERT_PATH
    if _CACERT_PATH is not None:
        return _CACERT_PATH

    digest = hashlib.sha256(_CACERT_PEM.encode("ascii")).hexdigest()[:16]
    path = os.path.join(tempfile.gettempdir(), f"staticpython-certifi-{{digest}}.pem")
    try:
        with open(path, "r", encoding="ascii") as existing:
            if existing.read() == _CACERT_PEM:
                _CACERT_PATH = path
                return _CACERT_PATH
    except OSError:
        pass

    with open(path, "w", encoding="ascii", newline="\\n") as output:
        output.write(_CACERT_PEM)
    _CACERT_PATH = path
    return _CACERT_PATH


def contents() -> str:
    return _CACERT_PEM
''',
        encoding="utf-8",
        newline="\n",
    )
    context.log(f"embedded certifi cacert bundle into {core_path.relative_to(context.source_root)}")


LIBRARY_INTEGRATION = simple_library(
    name='certifi',
    overlay_entries=['Lib/certifi'],
    post_patch_hooks=[embed_cacert_pem],
    verification_steps=[
        inline_verification_step(
            "certifi-smoke",
            """
from pathlib import Path
import certifi

path = Path(certifi.where())
contents = certifi.contents()
assert path.exists()
assert "BEGIN CERTIFICATE" in contents
assert path.read_text(encoding="ascii") == contents
""",
        )
    ],
)
