from libs import LibraryHookContext, simple_library


def embed_cacert_pem(context: LibraryHookContext) -> None:
    package_dir = context.source_root / "Lib" / "certifi"
    certifi_dir = package_dir
    cacert_path = certifi_dir / "cacert.pem"
    if not cacert_path.exists():
        certifi_dir = context.source_root / "Lib"
        cacert_path = certifi_dir / "cacert.pem"
    if not cacert_path.exists():
        raise RuntimeError("certifi cacert.pem was not materialized")
    weak_path = certifi_dir / "weak.pem"
    core_path = package_dir / "core.py"
    cacert_pem = cacert_path.read_bytes()
    weak_pem = weak_path.read_bytes() if weak_path.exists() else None
    embedded = repr(cacert_pem)
    weak_embedded = repr(weak_pem)
    core_path.write_text(
        f'''"""
certifi.py
~~~~~~~~~~

Single-file friendly certifi core generated by StaticPython.
"""

import hashlib
import os
import tempfile
import warnings


_CACERT_PEM = {embedded}
_WEAK_PEM = {weak_embedded}
_CACERT_PATH = None
_WEAK_PATH = None


class DeprecatedBundleWarning(DeprecationWarning):
    """
    The weak security bundle is being deprecated. Please bother your service
    provider to get them to stop using cross-signed roots.
    """


def _materialize_bundle(payload: bytes, label: str) -> str:
    digest = hashlib.sha256(payload).hexdigest()[:16]
    path = os.path.join(tempfile.gettempdir(), f"staticpython-certifi-{{label}}-{{digest}}.pem")
    try:
        with open(path, "rb") as existing:
            if existing.read() == payload:
                return path
    except OSError:
        pass

    with open(path, "wb") as output:
        output.write(payload)
    return path


def where() -> str:
    global _CACERT_PATH
    if _CACERT_PATH is not None:
        return _CACERT_PATH

    _CACERT_PATH = _materialize_bundle(_CACERT_PEM, "cacert")
    return _CACERT_PATH


def old_where() -> str:
    global _WEAK_PATH
    warnings.warn(
        "The weak security bundle is being deprecated.",
        DeprecatedBundleWarning
    )
    if _WEAK_PEM is None:
        return where()
    if _WEAK_PATH is None:
        _WEAK_PATH = _materialize_bundle(_WEAK_PEM, "weak")
    return _WEAK_PATH


def contents() -> str:
    return _CACERT_PEM.decode("utf-8")
''',
        encoding="utf-8",
        newline="\n",
    )
    context.log(f"embedded certifi cacert bundle into {core_path.relative_to(context.source_root)}")


LIBRARY_INTEGRATION = simple_library(
    name='certifi',
    source_mapping={
        "certifi": "Lib/certifi",
        "?cacert.pem": "Lib/certifi/cacert.pem",
        "?weak.pem": "Lib/certifi/weak.pem",
    },
    post_patch_hooks=[embed_cacert_pem],
)
