from libs import simple_library, source_path, transform_source_text, write_source_text


def embed_parso_grammars(context) -> None:
    grammar_root = source_path(context, "Lib/parso/python")
    grammars = {
        f"python/{path.name}": path.read_text(encoding="utf-8")
        for path in sorted(grammar_root.glob("grammar*.txt"))
    }
    if not grammars or "python/grammar313.txt" not in grammars:
        raise RuntimeError("expected Parso grammar files were not materialized")

    write_source_text(
        context,
        "Lib/parso/_staticpython_grammars.py",
        "# Generated by StaticPython; keeps Parso grammar files available after freezing.\n"
        f"GRAMMARS = {grammars!r}\n",
    )

    def patch_grammar(text: str) -> str:
        text = text.replace(
            "from parso.pgen2 import generate_grammar\n",
            "from parso.pgen2 import generate_grammar\nfrom parso._staticpython_grammars import GRAMMARS as _STATICPYTHON_GRAMMARS\n",
            1,
        )
        if "_STATICPYTHON_GRAMMARS" not in text:
            raise RuntimeError("failed to patch Parso static grammar import")
        return text.replace(
            "        try:\n"
            "            with open(path) as f:\n"
            "                bnf_text = f.read()\n"
            "\n"
            "            grammar = PythonGrammar(version_info, bnf_text)\n"
            "            return _loaded_grammars.setdefault(path, grammar)\n"
            "        except FileNotFoundError:\n"
            "            message = \"Python version %s.%s is currently not supported.\" % (\n"
            "                version_info.major, version_info.minor\n"
            "            )\n"
            "            raise NotImplementedError(message)\n",
            "        try:\n"
            "            grammar_key = file.replace(os.sep, \"/\")\n"
            "            bnf_text = _STATICPYTHON_GRAMMARS.get(grammar_key)\n"
            "            if bnf_text is None:\n"
            "                with open(path) as f:\n"
            "                    bnf_text = f.read()\n"
            "\n"
            "            grammar = PythonGrammar(version_info, bnf_text)\n"
            "            return _loaded_grammars.setdefault(path, grammar)\n"
            "        except FileNotFoundError:\n"
            "            message = \"Python version %s.%s is currently not supported.\" % (\n"
            "                version_info.major, version_info.minor\n"
            "            )\n"
            "            raise NotImplementedError(message)\n",
            1,
        )

    transform_source_text(context, "Lib/parso/grammar.py", patch_grammar)


LIBRARY_INTEGRATION = simple_library(
    name="parso",
    overlay_entries=["Lib/parso"],
    materialized_paths=[
        "Lib/parso/python/grammar313.txt",
        "Lib/parso/python/grammar314.txt",
        "Lib/parso/_staticpython_grammars.py",
    ],
    post_patch_hooks=[embed_parso_grammars],
)
