from libs import replace_regex_once, simple_library, source_path, transform_source_text, write_source_text


def embed_parso_grammars(context) -> None:
    grammar_root = source_path(context, "Lib/parso/python")
    grammars = {
        f"python/{path.name}": path.read_text(encoding="utf-8")
        for path in sorted(grammar_root.glob("grammar*.txt"))
    }
    if not grammars:
        raise RuntimeError("expected Parso grammar files were not materialized")

    write_source_text(
        context,
        "Lib/parso/_staticpython_grammars.py",
        "# Generated by StaticPython; keeps Parso grammar files available after freezing.\n"
        f"GRAMMARS = {grammars!r}\n",
    )

    def patch_grammar(text: str) -> str:
        text = text.replace(
            "from parso.pgen2 import generate_grammar\n",
            "from parso.pgen2 import generate_grammar\nfrom parso._staticpython_grammars import GRAMMARS as _STATICPYTHON_GRAMMARS\n",
            1,
        )
        if "_STATICPYTHON_GRAMMARS" not in text:
            raise RuntimeError("failed to patch Parso static grammar import")
        return replace_regex_once(
            text,
            r"(?m)^(?P<indent>\s*)with open\(path\) as f:\n(?P=indent)\s{4}bnf_text = f\.read\(\)\n\n(?P=indent)grammar = PythonGrammar\(version_info, bnf_text\)\n(?P=indent)return _loaded_grammars\.setdefault\(path, grammar\)\n",
            "\\g<indent>grammar_key = file.replace(os.sep, \"/\")\n"
            "\\g<indent>bnf_text = _STATICPYTHON_GRAMMARS.get(grammar_key)\n"
            "\\g<indent>if bnf_text is None:\n"
            "\\g<indent>    with open(path) as f:\n"
            "\\g<indent>        bnf_text = f.read()\n\n"
            "\\g<indent>grammar = PythonGrammar(version_info, bnf_text)\n"
            "\\g<indent>return _loaded_grammars.setdefault(path, grammar)\n",
            label="Parso grammar loader body",
        )

    transform_source_text(context, "Lib/parso/grammar.py", patch_grammar)


LIBRARY_INTEGRATION = simple_library(
    name="parso",
    overlay_entries=["Lib/parso"],
    materialized_paths=[
        "Lib/parso",
        "Lib/parso/_staticpython_grammars.py",
    ],
    post_patch_hooks=[embed_parso_grammars],
)
