from __future__ import annotations

import re

from libs import replace_function_block_once, simple_library, source_path, transform_source_text, write_source_text


def embed_faker_provider_index(context) -> None:
    providers_root = source_path(context, "Lib/faker/providers")
    if not providers_root.exists():
        return
    loading_path = source_path(context, "Lib/faker/utils/loading.py")
    if not loading_path.exists():
        return
    providers: list[str] = []
    localized: dict[str, list[str]] = {}

    for init_file in sorted(providers_root.rglob("__init__.py")):
        relative = init_file.relative_to(providers_root)
        parts = relative.parts[:-1]
        if len(parts) == 1:
            providers.append(parts[0])
        elif len(parts) == 2:
            localized.setdefault(parts[0], []).append(parts[1])

    providers = sorted(set(providers))
    localized = {provider: sorted(set(locales)) for provider, locales in sorted(localized.items())}
    available_locales = sorted({locale for locales in localized.values() for locale in locales})
    if not providers:
        raise RuntimeError("expected Faker provider locale packages were not materialized")

    write_source_text(
        context,
        "Lib/faker/_staticpython_provider_index.py",
        "# Generated by StaticPython; keeps Faker provider discovery working after freezing.\n"
        f"PROVIDERS = {providers!r}\n"
        f"LOCALIZED_PROVIDERS = {localized!r}\n"
        f"AVAILABLE_LOCALES = {available_locales!r}\n",
    )

    def patch_loading(text: str) -> str:
        if re.search(r"(?m)^import os(?:\s|$)", text) is None:
            if "import pkgutil\n" in text:
                text = text.replace("import pkgutil\n", "import os\nimport pkgutil\n", 1)
            elif "import sys\n" in text:
                text = text.replace("import sys\n", "import os\nimport sys\n", 1)
            elif "from importlib import import_module\n" in text:
                text = text.replace("from importlib import import_module\n", "import os\nfrom importlib import import_module\n", 1)
            else:
                raise RuntimeError("faker provider index os import anchor not found")
        if "from faker._staticpython_provider_index import" not in text:
            static_index_import = (
                "\nfrom faker._staticpython_provider_index import "
                "LOCALIZED_PROVIDERS as _STATICPYTHON_LOCALIZED_PROVIDERS\n"
                "from faker._staticpython_provider_index import PROVIDERS as _STATICPYTHON_PROVIDERS\n"
            )
            updated, count = re.subn(
                r"(?m)^(from typing import .+\n)",
                r"\1" + static_index_import,
                text,
                count=1,
            )
            if count == 1:
                text = updated
            elif "from types import ModuleType\n" in text:
                text = text.replace("from types import ModuleType\n", "from types import ModuleType\n" + static_index_import, 1)
            elif "from importlib import import_module\n" in text:
                text = text.replace("from importlib import import_module\n", "from importlib import import_module\n" + static_index_import, 1)
            elif "import pkgutil\n" in text:
                text = text.replace("import pkgutil\n", "import pkgutil\n" + static_index_import, 1)
            else:
                raise RuntimeError("faker provider index import anchor not found")
        new_list_module = (
            "def list_module(module):\n"
            "    package = module.__package__ or module.__name__\n"
            "    if package == \"faker.providers\" and _STATICPYTHON_PROVIDERS:\n"
            "        return list(_STATICPYTHON_PROVIDERS)\n"
            "    if package.startswith(\"faker.providers.\"):\n"
            "        provider_name = package.rsplit(\".\", 1)[-1]\n"
            "        locales = _STATICPYTHON_LOCALIZED_PROVIDERS.get(provider_name)\n"
            "        if locales is not None:\n"
            "            return list(locales)\n"
            "\n"
            "    path = get_path(module)\n"
            "\n"
            "    if getattr(sys, \"_MEIPASS\", False):\n"
            "        # PyInstaller\n"
            "        if \"Path\" in globals():\n"
            "            return [file.parent.name for file in Path(path).glob(\"*/__init__.py\")]\n"
            "        return [\n"
            "            name\n"
            "            for name in os.listdir(path)\n"
            "            if os.path.isfile(os.path.join(path, name, \"__init__.py\"))\n"
            "        ]\n"
            "    return [name for _, name, is_pkg in pkgutil.iter_modules([str(path)]) if is_pkg]\n"
        )
        if "def list_module(" in text and "pkgutil.iter_modules" in text:
            return replace_function_block_once(
                text,
                "list_module",
                new_list_module + "\n\n",
                label="faker provider index list_module",
                next_name="find_available_locales",
            )
        if "_STATICPYTHON_PROVIDERS" not in text and "pkgutil.iter_modules" in text:
            raise RuntimeError("faker provider index list_module anchor not found")
        return text

    transform_source_text(context, "Lib/faker/utils/loading.py", patch_loading)


LIBRARY_INTEGRATION = simple_library(
    name="faker",
    project_name="Faker",
    overlay_entries=["Lib/faker"],
    post_patch_hooks=[embed_faker_provider_index],
)
