from __future__ import annotations

from libs import ensure_package_markers, pypi_library, replace_regex_once, transform_source_text


_CGI_COMPAT = (
    "try:\n"
    "    import cgi\n"
    "except ModuleNotFoundError:\n"
    "    class _StaticPythonCgi:\n"
    "        class FieldStorage:\n"
    "            def __init__(self, *args, **kwargs):\n"
    "                raise RuntimeError(\n"
    "                    'remi file uploads require cgi.FieldStorage, '\n"
    "                    'which is not available on this CPython version'\n"
    "                )\n"
    "    cgi = _StaticPythonCgi()\n"
)


def _patch_remi_init(text: str) -> str:
    text = ensure_package_markers(text, "remi")
    if "pkg_resources" not in text:
        return text
    return replace_regex_once(
        text,
        r"(?ms)^from pkg_resources import get_distribution, DistributionNotFound\s*"
        r"try:\s*"
        r"    __version__ = get_distribution\(__name__\)\.version\s*"
        r"except DistributionNotFound:\s*"
        r"    # package is not installed\s*"
        r"    pass\s*",
        "try:\n"
        "    from importlib.metadata import PackageNotFoundError, version\n"
        "except Exception:  # pragma: no cover - importlib.metadata is stdlib on supported CPython\n"
        "    PackageNotFoundError = Exception\n"
        "    version = None\n"
        "\n"
        "try:\n"
        "    __version__ = version(__name__) if version is not None else \"0+staticpython\"\n"
        "except PackageNotFoundError:\n"
        "    __version__ = \"0+staticpython\"\n",
        label="remi package metadata fallback",
    )


def _patch_remi_server(text: str) -> str:
    # CPython's _freeze_module can fail internally on Remi's raw non-ASCII URL regex.
    text = text.replace("£", "\\xa3").replace("°", "\\xb0").replace("§", "\\xa7")
    if "import cgi" in text and "_StaticPythonCgi" not in text:
        text = replace_regex_once(
            text,
            r"(?m)^import cgi\s*$",
            _CGI_COMPAT,
            label="remi cgi compatibility",
        )
    if "_STATICPYTHON_REMI_SERVER_SOURCE" in text:
        return text
    return (
        "# Generated by StaticPython; keep remi.server importable while avoiding a _freeze_module crash.\n"
        f"_STATICPYTHON_REMI_SERVER_SOURCE = {text!r}\n"
        "_STATICPYTHON_REMI_SERVER_FILENAME = globals().get('__file__', 'remi/server.py')\n"
        "exec(compile(_STATICPYTHON_REMI_SERVER_SOURCE, _STATICPYTHON_REMI_SERVER_FILENAME, 'exec'), globals(), globals())\n"
    )


def patch_remi_sources(context) -> None:
    transform_source_text(context, "Lib/remi/__init__.py", _patch_remi_init)
    transform_source_text(context, "Lib/remi/server.py", _patch_remi_server, allow_missing=True)


LIBRARY_INTEGRATION = pypi_library(
    name="remi",
    source_mapping={
        "remi": "Lib/remi",
    },
    python_packages=["remi"],
    post_patch_hooks=[patch_remi_sources],
)
