from __future__ import annotations

import json

from libs import (
    ensure_text_after,
    pypi_library,
    replace_function_block_once,
    source_path,
    transform_source_text,
    write_source_text,
)


def embed_jsonschema_specifications(context) -> None:
    package_root = source_path(context, "Lib/jsonschema_specifications")
    schema_root = package_root / "schemas"
    if not schema_root.is_dir():
        raise RuntimeError("jsonschema-specifications schema directory is missing")
    schemas: dict[str, object] = {}
    for path in sorted(schema_root.rglob("*")):
        if not path.is_file() or path.name.startswith("."):
            continue
        relative = path.relative_to(schema_root).as_posix()
        schemas[relative] = json.loads(path.read_text(encoding="utf-8"))
    if not schemas:
        raise RuntimeError("jsonschema-specifications contained no schemas to embed")

    write_source_text(
        context,
        "Lib/jsonschema_specifications/_static_schemas.py",
        "# Generated by StaticPython; avoids filesystem resource traversal at runtime.\n"
        f"SCHEMAS = {schemas!r}\n",
    )

    def patch_core(text: str) -> str:
        if (
            "from ._static_schemas import SCHEMAS as _STATICPYTHON_SCHEMAS\n"
            not in text
        ):
            text = ensure_text_after(
                text,
                "from referencing import Resource\n",
                "\nfrom ._static_schemas import SCHEMAS as _STATICPYTHON_SCHEMAS\n",
                label="jsonschema-specifications embedded schema import",
            )
        return replace_function_block_once(
            text,
            "_schemas",
            "def _schemas():\n"
            '    """Yield every embedded official JSON Schema resource."""\n'
            "    for path in sorted(_STATICPYTHON_SCHEMAS):\n"
            "        yield Resource.from_contents(_STATICPYTHON_SCHEMAS[path])\n",
            label="jsonschema-specifications schema traversal",
        )

    transform_source_text(
        context,
        "Lib/jsonschema_specifications/_core.py",
        patch_core,
    )


LIBRARY_INTEGRATION = pypi_library(
    name="jsonschema_specifications",
    project_name="jsonschema-specifications",
    release_version="2025.9.1",
    source_archive_sha256_by_version={
        "2025.9.1": "b540987f239e745613c7a9176f3edb72b832a4ac465cf02712288397832b5e8d",
    },
    source_mapping={
        "jsonschema_specifications": "Lib/jsonschema_specifications",
    },
    materialized_paths=[
        "Lib/jsonschema_specifications/_static_schemas.py",
    ],
    python_packages=["jsonschema_specifications"],
    post_patch_hooks=[embed_jsonschema_specifications],
    license_expression="MIT",
    smoke_tests=[
        {
            "name": "draft-2020-12-registry",
            "kind": "inline",
            "code": (
                "from jsonschema_specifications import REGISTRY; "
                "schema=REGISTRY.contents('https://json-schema.org/draft/2020-12/schema'); "
                "assert schema['$id'] == 'https://json-schema.org/draft/2020-12/schema'"
            ),
        }
    ],
)
