from libs import (
    inline_verification_step,
    replace_text_once,
    script_verification_step,
    simple_library,
    source_path,
    transform_source_text,
    write_source_text,
)


def patch_nbconvert_sources(context) -> None:
    templates_root = source_path(context, "share/jupyter/nbconvert/templates")
    templates = {
        path.relative_to(templates_root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(templates_root.rglob("*"))
        if path.is_file() and path.suffix.lower() in {".j2", ".json", ".tpl", ".css", ".md"}
    }
    confs = {
        template_name: templates[f"{template_name}/conf.json"]
        for template_name in sorted({key.split("/", 1)[0] for key in templates})
        if f"{template_name}/conf.json" in templates
    }
    template_names = sorted({key.split("/", 1)[0] for key in templates})
    if "lab/index.html.j2" not in templates or "base/display_priority.j2" not in templates:
        raise RuntimeError("expected nbconvert templates were not materialized")

    write_source_text(
        context,
        "Lib/nbconvert/_staticpython_templates.py",
        "# Generated by StaticPython; keeps nbconvert templates available after freezing.\n"
        f"TEMPLATES = {templates!r}\n"
        f"CONFS = {confs!r}\n"
        f"TEMPLATE_NAMES = {template_names!r}\n",
    )

    def patch_exporter_base(text: str) -> str:
        text = replace_text_once(
            text,
            "from .exporter import Exporter\n",
            """from .exporter import Exporter


_STATICPYTHON_EXPORTERS = {
    "asciidoc": "nbconvert.exporters.asciidoc.ASCIIDocExporter",
    "custom": "nbconvert.exporters.templateexporter.TemplateExporter",
    "html": "nbconvert.exporters.html.HTMLExporter",
    "latex": "nbconvert.exporters.latex.LatexExporter",
    "markdown": "nbconvert.exporters.markdown.MarkdownExporter",
    "notebook": "nbconvert.exporters.notebook.NotebookExporter",
    "pdf": "nbconvert.exporters.pdf.PDFExporter",
    "python": "nbconvert.exporters.python.PythonExporter",
    "qtpdf": "nbconvert.exporters.qtpdf.QtPDFExporter",
    "qtpng": "nbconvert.exporters.qtpng.QtPNGExporter",
    "rst": "nbconvert.exporters.rst.RSTExporter",
    "script": "nbconvert.exporters.script.ScriptExporter",
    "slides": "nbconvert.exporters.slides.SlidesExporter",
    "webpdf": "nbconvert.exporters.webpdf.WebPDFExporter",
}


class _StaticPythonExporterEntryPoint:
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def load(self):
        return import_item(self.value)


def _iter_exporter_entries():
    exporters = list(entry_points(group="nbconvert.exporters"))
    if exporters:
        return exporters
    return [
        _StaticPythonExporterEntryPoint(name, value)
        for name, value in _STATICPYTHON_EXPORTERS.items()
    ]
""",
            label="nbconvert exporter fallback helpers",
        )
        text = replace_text_once(
            text,
            '        exporters = entry_points(group="nbconvert.exporters")\n',
            '        exporters = _iter_exporter_entries()\n',
            label="nbconvert get_exporter fallback call",
        )
        return replace_text_once(
            text,
            '    exporters = sorted(e.name for e in entry_points(group="nbconvert.exporters"))\n',
            '    exporters = sorted(e.name for e in _iter_exporter_entries())\n',
            label="nbconvert get_export_names fallback call",
        )

    transform_source_text(context, "Lib/nbconvert/exporters/base.py", patch_exporter_base)

    def patch_template_exporter(text: str) -> str:
        text = replace_text_once(
            text,
            "from .exporter import Exporter\n",
            "from .exporter import Exporter\nfrom nbconvert._staticpython_templates import CONFS as _STATICPYTHON_TEMPLATE_CONFS\nfrom nbconvert._staticpython_templates import TEMPLATE_NAMES as _STATICPYTHON_TEMPLATE_NAMES\nfrom nbconvert._staticpython_templates import TEMPLATES as _STATICPYTHON_TEMPLATES\n",
            label="nbconvert template exporter static imports",
        )
        text = replace_text_once(
            text,
            "        loaders = [\n"
            "            *self.extra_loaders,\n"
            "            ExtensionTolerantLoader(FileSystemLoader(paths), self.template_extension),\n"
            "            DictLoader({self._raw_template_key: self.raw_template}),\n"
            "        ]\n",
            "        loaders = [\n"
            "            *self.extra_loaders,\n"
            "            ExtensionTolerantLoader(DictLoader(_STATICPYTHON_TEMPLATES), self.template_extension),\n"
            "            ExtensionTolerantLoader(FileSystemLoader(paths), self.template_extension),\n"
            "            DictLoader({self._raw_template_key: self.raw_template}),\n"
            "        ]\n",
            label="nbconvert embedded jinja template loader",
        )
        text = replace_text_once(
            text,
            "        conf: dict[str, t.Any] = {}  # the configuration once all conf files are merged\n"
            "        for path in map(Path, self.template_paths):\n"
            "            conf_path = path / \"conf.json\"\n"
            "            try:\n"
            "                conf_path_exists = conf_path.exists()\n"
            "            except PermissionError:\n"
            "                # for Python <3.14\n"
            "                pass\n"
            "            else:\n"
            "                if conf_path_exists:\n"
            "                    with conf_path.open() as f:\n"
            "                        conf = recursive_update(conf, json.load(f))\n"
            "        return conf\n",
            "        conf: dict[str, t.Any] = {}  # the configuration once all conf files are merged\n"
            "        for template_name in reversed(self.get_template_names()):\n"
            "            conf_text = _STATICPYTHON_TEMPLATE_CONFS.get(template_name)\n"
            "            if conf_text:\n"
            "                conf = recursive_update(conf, json.loads(conf_text))\n"
            "        for path in map(Path, self.template_paths):\n"
            "            conf_path = path / \"conf.json\"\n"
            "            try:\n"
            "                conf_path_exists = conf_path.exists()\n"
            "            except PermissionError:\n"
            "                # for Python <3.14\n"
            "                pass\n"
            "            else:\n"
            "                if conf_path_exists:\n"
            "                    with conf_path.open() as f:\n"
            "                        conf = recursive_update(conf, json.load(f))\n"
            "        return conf\n",
            label="nbconvert embedded template conf loader",
        )
        text = replace_text_once(
            text,
            "                if not found_at_least_one:\n"
            "                    paths = \"\\n\\t\".join(root_dirs)\n"
            "                    msg = f\"No template sub-directory with name {base_template!r} found in the following paths:\\n\\t{paths}\"\n"
            "                    raise ValueError(msg)\n"
            "            merged_conf = recursive_update(dict(conf), merged_conf)\n"
            "            base_template = t.cast(t.Any, conf.get(\"base_template\"))\n",
            "                if not found_at_least_one:\n"
            "                    static_conf_text = _STATICPYTHON_TEMPLATE_CONFS.get(base_template)\n"
            "                    if static_conf_text is not None or base_template in _STATICPYTHON_TEMPLATE_NAMES:\n"
            "                        found_at_least_one = True\n"
            "                        if static_conf_text is not None:\n"
            "                            conf = recursive_update(json.loads(static_conf_text), conf)\n"
            "                if not found_at_least_one:\n"
            "                    paths = \"\\n\\t\".join(root_dirs)\n"
            "                    msg = f\"No template sub-directory with name {base_template!r} found in the following paths:\\n\\t{paths}\"\n"
            "                    raise ValueError(msg)\n"
            "            merged_conf = recursive_update(dict(conf), merged_conf)\n"
            "            base_template = t.cast(t.Any, conf.get(\"base_template\"))\n",
            label="nbconvert embedded template name discovery",
        )
        return replace_text_once(
            text,
            "        additional_paths = []\n"
            "        for path in self.template_data_paths:\n"
            "            if not prune or os.path.exists(path):\n"
            "                additional_paths.append(path)\n"
            "\n"
            "        return paths + self.extra_template_paths + additional_paths\n",
            "        additional_paths = []\n"
            "        for path in self.template_data_paths:\n"
            "            if not prune or os.path.exists(path):\n"
            "                additional_paths.append(path)\n"
            "\n"
            "        if _STATICPYTHON_TEMPLATES:\n"
            "            additional_paths.append(\"staticpython-nbconvert-templates\")\n"
            "        return paths + self.extra_template_paths + additional_paths\n",
            label="nbconvert embedded template path marker",
        )

    transform_source_text(context, "Lib/nbconvert/exporters/templateexporter.py", patch_template_exporter)


LIBRARY_INTEGRATION = simple_library(
    name="nbconvert",
    source_mapping={
        "nbconvert": "Lib/nbconvert",
        "share/templates": "share/jupyter/nbconvert/templates",
    },
    materialized_paths=["Lib/nbconvert/_staticpython_templates.py"],
    verification_materialized_paths=[
        "Lib/nbconvert",
        "share/jupyter/nbconvert/templates/lab/index.html.j2",
        "share/jupyter/nbconvert/templates/base/display_priority.j2",
    ],
    post_patch_hooks=[patch_nbconvert_sources],
    verification_steps=[
        inline_verification_step(
            "nbconvert-smoke",
            """
from nbformat import v4
from nbconvert.exporters import HTMLExporter, ScriptExporter
from nbconvert.exporters.base import get_export_names, get_exporter

notebook = v4.new_notebook()
notebook.cells.append(v4.new_markdown_cell("# StaticPython"))
notebook.cells.append(v4.new_code_cell("answer = 40 + 2\\nanswer"))

export_names = set(get_export_names())
assert {"notebook"} <= export_names
assert get_exporter("html").__name__ == "HTMLExporter"
script_exporter_class = get_exporter("script")
assert script_exporter_class.__name__ in {"ScriptExporter", "PythonExporter"}

html_exporter = HTMLExporter()
html_body, html_resources = html_exporter.from_notebook_node(notebook)
assert "<h1" in html_body and "StaticPython" in html_body
assert html_exporter.get_template_names()[0] == "lab"
assert '<div class="highlight hl-ipython3"><pre>' in html_body
assert "answer" in html_body and "40" in html_body and "2" in html_body
assert isinstance(html_resources, dict)

script_exporter = ScriptExporter()
script_body, script_resources = script_exporter.from_notebook_node(notebook)
assert "answer = 40 + 2" in script_body
assert script_resources.get("output_extension") in {".txt", ".py"}
""",
            timeout=600,
        ),
        script_verification_step(
            "nbconvert-runtime",
            "scripts/nbconvert_runtime.py",
            timeout=600,
        ),
    ],
)
