from libs import replace_regex_once, replace_text_once, simple_library, source_path, transform_source_text, write_source_text


def patch_nbconvert_sources(context) -> None:
    templates_root = source_path(context, "share/jupyter/nbconvert/templates")
    templates = {
        path.relative_to(templates_root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(templates_root.rglob("*"))
        if path.is_file() and path.suffix.lower() in {".j2", ".json", ".tpl", ".css", ".md"}
    }
    confs = {
        template_name: templates[f"{template_name}/conf.json"]
        for template_name in sorted({key.split("/", 1)[0] for key in templates})
        if f"{template_name}/conf.json" in templates
    }
    template_names = sorted({key.split("/", 1)[0] for key in templates})
    modern_template_layout = "lab/index.html.j2" in templates and "base/display_priority.j2" in templates
    if not templates:
        raise RuntimeError("expected nbconvert templates were not materialized")
    if modern_template_layout is False and "classic/index.html.j2" in templates:
        modern_template_layout = True
    if modern_template_layout and (
        "lab/index.html.j2" not in templates or "base/display_priority.j2" not in templates
    ):
        raise RuntimeError("expected nbconvert templates were not materialized")

    write_source_text(
        context,
        "Lib/nbconvert/_staticpython_templates.py",
        "# Generated by StaticPython; keeps nbconvert templates available after freezing.\n"
        f"TEMPLATES = {templates!r}\n"
        f"CONFS = {confs!r}\n"
        f"TEMPLATE_NAMES = {template_names!r}\n",
    )

    def patch_exporter_base(text: str) -> str:
        if "from .exporter import Exporter\n" not in text:
            return text
        text = replace_text_once(
            text,
            "from .exporter import Exporter\n",
            """from .exporter import Exporter


_STATICPYTHON_EXPORTERS = {
    "asciidoc": "nbconvert.exporters.asciidoc.ASCIIDocExporter",
    "custom": "nbconvert.exporters.templateexporter.TemplateExporter",
    "html": "nbconvert.exporters.html.HTMLExporter",
    "latex": "nbconvert.exporters.latex.LatexExporter",
    "markdown": "nbconvert.exporters.markdown.MarkdownExporter",
    "notebook": "nbconvert.exporters.notebook.NotebookExporter",
    "pdf": "nbconvert.exporters.pdf.PDFExporter",
    "python": "nbconvert.exporters.python.PythonExporter",
    "qtpdf": "nbconvert.exporters.qtpdf.QtPDFExporter",
    "qtpng": "nbconvert.exporters.qtpng.QtPNGExporter",
    "rst": "nbconvert.exporters.rst.RSTExporter",
    "script": "nbconvert.exporters.script.ScriptExporter",
    "slides": "nbconvert.exporters.slides.SlidesExporter",
    "webpdf": "nbconvert.exporters.webpdf.WebPDFExporter",
}


class _StaticPythonExporterEntryPoint:
    def __init__(self, name, value):
        self.name = name
        self.value = value

    def load(self):
        return import_item(self.value)


def _iter_exporter_entries():
    exporters = list(entry_points(group="nbconvert.exporters"))
    if exporters:
        return exporters
    return [
        _StaticPythonExporterEntryPoint(name, value)
        for name, value in _STATICPYTHON_EXPORTERS.items()
    ]
""",
            label="nbconvert exporter fallback helpers",
        )
        text = replace_text_once(
            text,
            '        exporters = entry_points(group="nbconvert.exporters")\n',
            '        exporters = _iter_exporter_entries()\n',
            label="nbconvert get_exporter fallback call",
        )
        return replace_text_once(
            text,
            '    exporters = sorted(e.name for e in entry_points(group="nbconvert.exporters"))\n',
            '    exporters = sorted(e.name for e in _iter_exporter_entries())\n',
            label="nbconvert get_export_names fallback call",
        )

    transform_source_text(context, "Lib/nbconvert/exporters/base.py", patch_exporter_base, allow_missing=True)

    def patch_template_exporter(text: str) -> str:
        text = replace_text_once(
            text,
            "from .exporter import Exporter\n",
            "from .exporter import Exporter\nfrom nbconvert._staticpython_templates import CONFS as _STATICPYTHON_TEMPLATE_CONFS\nfrom nbconvert._staticpython_templates import TEMPLATE_NAMES as _STATICPYTHON_TEMPLATE_NAMES\nfrom nbconvert._staticpython_templates import TEMPLATES as _STATICPYTHON_TEMPLATES\n",
            label="nbconvert template exporter static imports",
        )
        if "def _get_conf(" not in text:
            return text
        text = replace_text_once(
            text,
            "        loaders = [\n"
            "            *self.extra_loaders,\n"
            "            ExtensionTolerantLoader(FileSystemLoader(paths), self.template_extension),\n"
            "            DictLoader({self._raw_template_key: self.raw_template}),\n"
            "        ]\n",
            "        static_templates = dict(_STATICPYTHON_TEMPLATES)\n"
            "        for template_name in self.get_template_names():\n"
            "            prefix = template_name + \"/\"\n"
            "            for key, value in _STATICPYTHON_TEMPLATES.items():\n"
            "                if key.startswith(prefix):\n"
            "                    static_templates.setdefault(key[len(prefix):], value)\n"
            "\n"
            "        loaders = [\n"
            "            *self.extra_loaders,\n"
            "            ExtensionTolerantLoader(DictLoader(static_templates), self.template_extension),\n"
            "            ExtensionTolerantLoader(FileSystemLoader(paths), self.template_extension),\n"
            "            DictLoader({self._raw_template_key: self.raw_template}),\n"
            "        ]\n",
            label="nbconvert embedded jinja template loader",
        )
        text = replace_regex_once(
            text,
            r"(?ms)^    def _get_conf\(self\):\n.*?^    @default\(\"template_paths\"\)\n",
            """    def _get_conf(self):
        conf: dict[str, t.Any] = {}  # the configuration once all conf files are merged
        for template_name in reversed(self.get_template_names()):
            conf_text = _STATICPYTHON_TEMPLATE_CONFS.get(template_name)
            if conf_text:
                conf = recursive_update(conf, json.loads(conf_text))
        for path in map(Path, self.template_paths):
            conf_path = path / "conf.json"
            try:
                conf_path_exists = conf_path.exists()
            except PermissionError:
                # for Python <3.14
                pass
            else:
                if conf_path_exists:
                    with conf_path.open() as f:
                        conf = recursive_update(conf, json.load(f))
        return conf

    @default("template_paths")
""",
            label="nbconvert embedded template conf loader",
        )
        text = replace_text_once(
            text,
            "                if not found_at_least_one:\n"
            "                    paths = \"\\n\\t\".join(root_dirs)\n"
            "                    msg = f\"No template sub-directory with name {base_template!r} found in the following paths:\\n\\t{paths}\"\n"
            "                    raise ValueError(msg)\n"
            "            merged_conf = recursive_update(dict(conf), merged_conf)\n"
            "            base_template = t.cast(t.Any, conf.get(\"base_template\"))\n",
            "                if not found_at_least_one:\n"
            "                    static_conf_text = _STATICPYTHON_TEMPLATE_CONFS.get(base_template)\n"
            "                    if static_conf_text is not None or base_template in _STATICPYTHON_TEMPLATE_NAMES:\n"
            "                        found_at_least_one = True\n"
            "                        if static_conf_text is not None:\n"
            "                            conf = recursive_update(json.loads(static_conf_text), conf)\n"
            "                if not found_at_least_one:\n"
            "                    paths = \"\\n\\t\".join(root_dirs)\n"
            "                    msg = f\"No template sub-directory with name {base_template!r} found in the following paths:\\n\\t{paths}\"\n"
            "                    raise ValueError(msg)\n"
            "            merged_conf = recursive_update(dict(conf), merged_conf)\n"
            "            base_template = t.cast(t.Any, conf.get(\"base_template\"))\n",
            label="nbconvert embedded template name discovery",
        )
        return replace_regex_once(
            text,
            r"(?ms)^    def _template_paths\(self, prune=True, root_dirs=None\):\n.*?^    @classmethod\n",
            """    def _template_paths(self, prune=True, root_dirs=None):
        paths = []
        root_dirs = self.get_prefix_root_dirs()
        template_names = self.get_template_names()
        for template_name in template_names:
            for base_dir in self.extra_template_basedirs:
                path = os.path.join(base_dir, template_name)
                try:
                    if not prune or os.path.exists(path):
                        paths.append(path)
                except PermissionError:
                    pass
            for root_dir in root_dirs:
                base_dir = os.path.join(root_dir, "nbconvert", "templates")
                path = os.path.join(base_dir, template_name)
                try:
                    if not prune or os.path.exists(path):
                        paths.append(path)
                except PermissionError:
                    pass

        for root_dir in root_dirs:
            paths.append(root_dir)
            base_dir = os.path.join(root_dir, "nbconvert", "templates")
            paths.append(base_dir)

            compatibility_dir = os.path.join(root_dir, "nbconvert", "templates", "compatibility")
            paths.append(compatibility_dir)

        additional_paths = []
        for path in self.template_data_paths:
            if not prune or os.path.exists(path):
                additional_paths.append(path)

        if _STATICPYTHON_TEMPLATES:
            additional_paths.append("staticpython-nbconvert-templates")
        return paths + self.extra_template_paths + additional_paths

    @classmethod
""",
            label="nbconvert embedded template path marker",
        )

    transform_source_text(context, "Lib/nbconvert/exporters/templateexporter.py", patch_template_exporter)


LIBRARY_INTEGRATION = simple_library(
    name="nbconvert",
    source_mapping={
        "nbconvert": "Lib/nbconvert",
        "share/templates": "share/jupyter/nbconvert/templates",
    },
    materialized_paths=["Lib/nbconvert/_staticpython_templates.py"],
    post_patch_hooks=[patch_nbconvert_sources],
)
