from __future__ import annotations

from libs import simple_library, source_path, transform_source_text, write_source_text


def embed_docutils_resources(context) -> None:
    package_root = source_path(context, "Lib/docutils")
    resources = {
        path.relative_to(package_root).as_posix(): path.read_text(encoding="utf-8")
        for path in sorted(package_root.rglob("*"))
        if path.is_file() and path.suffix.lower() in {".txt", ".css", ".tex", ".sty"}
    }
    if "writers/html5_polyglot/template.txt" not in resources:
        raise RuntimeError("expected Docutils HTML5 template was not materialized")

    write_source_text(
        context,
        "Lib/docutils/_staticpython_resources.py",
        "# Generated by StaticPython; keeps Docutils packaged text resources available after freezing.\n"
        f"RESOURCES = {resources!r}\n\n"
        "def resource_text(path: str) -> str | None:\n"
        "    return RESOURCES.get(path.replace('\\\\', '/'))\n",
    )

    def patch_html_base(text: str) -> str:
        text = text.replace(
            "import docutils\n",
            "import docutils\nfrom docutils._staticpython_resources import resource_text as _staticpython_resource_text\n",
            1,
        )
        text = text.replace(
            "    def apply_template(self) -> str:\n"
            "        template_path = Path(self.document.settings.template)\n"
            "        template = template_path.read_text(encoding='utf-8')\n"
            "        return template % self.interpolation_dict()\n",
            "    def apply_template(self) -> str:\n"
            "        template_path = Path(self.document.settings.template)\n"
            "        resource_key = template_path.as_posix().split('/docutils/', 1)[-1]\n"
            "        template = _staticpython_resource_text(resource_key)\n"
            "        if template is None:\n"
            "            template = template_path.read_text(encoding='utf-8')\n"
            "        return template % self.interpolation_dict()\n",
            1,
        )
        return text.replace(
            "                content = Path(path).read_text(encoding='utf-8')\n",
            "                stylesheet_path = Path(path)\n"
            "                resource_key = stylesheet_path.as_posix().split('/docutils/', 1)[-1]\n"
            "                content = _staticpython_resource_text(resource_key)\n"
            "                if content is None and stylesheet_path.name == path:\n"
            "                    for candidate in (\n"
            "                        f'writers/html5_polyglot/{path}',\n"
            "                        f'writers/html4css1/{path}',\n"
            "                        f'writers/pep_html/{path}',\n"
            "                    ):\n"
            "                        content = _staticpython_resource_text(candidate)\n"
            "                        if content is not None:\n"
            "                            break\n"
            "                if content is None:\n"
            "                    content = stylesheet_path.read_text(encoding='utf-8')\n",
            1,
        )

    transform_source_text(context, "Lib/docutils/writers/_html_base.py", patch_html_base)


LIBRARY_INTEGRATION = simple_library(
    name="docutils",
    overlay_entries=["Lib/docutils"],
    materialized_paths=["Lib/docutils/_staticpython_resources.py"],
    post_patch_hooks=[embed_docutils_resources],
)
