import json

from packaging.version import Version

from libs import (
    LibraryIntegration,
    replace_function_block_once,
    _candidate_pypi_archives,
    _copy_entry,
    _download_file,
    _extract_archive,
    _normalized_project_name,
    _resolve_source_entry,
    configure_python_module_ownership,
    transform_first_existing_source_text,
    replace_text_once,
    source_path,
    transform_source_text,
    write_source_text,
)


def _configure_black_version_module(enabled: bool) -> None:
    configure_python_module_ownership(
        LIBRARY_INTEGRATION,
        module_name="_black_version",
        materialized_path="Lib/_black_version.py",
        enabled=enabled,
    )


def _candidate_archives(context, project_name: str, release_version: str | None):
    target_version = Version(".".join(str(part) for part in context.version_info))
    return _candidate_pypi_archives(
        context.download_cache_root,
        project_name,
        target_version,
        release_version,
    )


def prepare_black_source(context) -> None:
    integration = LIBRARY_INTEGRATION
    project_name = integration.project_name or integration.name
    normalized = _normalized_project_name(project_name)
    release_version = integration.release_version
    candidate_archives = _candidate_archives(context, project_name, release_version)

    failures: list[str] = []
    for resolved_release_version, archive_path, url, cached in candidate_archives:
        extract_root = (
            context.work_cache_root
            / "pypi"
            / normalized
            / resolved_release_version
            / "extracted"
            / archive_path.name
        )
        if not archive_path.exists():
            context.log(f"downloading {project_name} {resolved_release_version} from PyPI")
            assert url is not None
            _download_file(url, archive_path)
        elif cached:
            context.log(f"reusing cached {project_name} {resolved_release_version} archive without refreshing PyPI metadata")
        else:
            context.log(f"reusing cached {project_name} {resolved_release_version} archive")

        try:
            extracted_root = _extract_archive(archive_path, extract_root, context.log)
            context.log(f"using {project_name} {resolved_release_version} source from {extracted_root}")

            try:
                _copy_entry(_resolve_source_entry(extracted_root, "_black_version.py||src/_black_version.py"), context.source_root / "Lib" / "_black_version.py")
                _copy_entry(_resolve_source_entry(extracted_root, "black||src/black"), context.source_root / "Lib" / "black")
                _copy_entry(_resolve_source_entry(extracted_root, "blackd||src/blackd"), context.source_root / "Lib" / "blackd")
                _copy_entry(_resolve_source_entry(extracted_root, "blib2to3||src/blib2to3"), context.source_root / "Lib" / "blib2to3")
                _configure_black_version_module(True)
            except RuntimeError:
                (context.source_root / "Lib" / "_black_version.py").unlink(missing_ok=True)
                _copy_entry(_resolve_source_entry(extracted_root, "black.py"), context.source_root / "Lib" / "black.py")
                _copy_entry(_resolve_source_entry(extracted_root, "blib2to3"), context.source_root / "Lib" / "blib2to3")
                _configure_black_version_module(False)
            return
        except RuntimeError as exc:
            failures.append(f"{archive_path.name}: {exc}")
            context.log(f"distribution candidate failed for {project_name} {resolved_release_version}: {archive_path.name}: {exc}")

    target_description = f" release {release_version!r}" if release_version is not None else ""
    raise RuntimeError(
        f"all compatible PyPI distribution artifacts failed for {project_name!r}{target_description}: "
        + "; ".join(failures)
    )


def patch_black_sources(context) -> None:
    grammar_text = {
        "Grammar.txt": source_path(context, "Lib/blib2to3/Grammar.txt").read_text(encoding="utf-8"),
        "PatternGrammar.txt": source_path(context, "Lib/blib2to3/PatternGrammar.txt").read_text(encoding="utf-8"),
    }
    schema_path = source_path(context, "Lib/black/resources/black.schema.json")
    schema = json.loads(schema_path.read_text(encoding="utf-8")) if schema_path.exists() else None
    write_source_text(
        context,
        "Lib/blib2to3/_staticpython_grammars.py",
        "# Generated by StaticPython; keeps Black's blib2to3 grammars available after freezing.\n"
        f"GRAMMAR_TEXT = {grammar_text!r}\n",
    )
    if schema is not None:
        write_source_text(
            context,
            "Lib/black/resources/_staticpython_schema.py",
            "# Generated by StaticPython; keeps Black's JSON schema available after freezing.\n"
            f"SCHEMA = {schema!r}\n",
        )

    def patch_linegen(text: str) -> str:
        if not text:
            return text
        replacement = "        _empty_parens: set[str] = set()\n"
        if "        \u00d8: set[str] = set()\n" in text:
            text = replace_text_once(
                text,
                "        \u00d8: set[str] = set()\n",
                replacement,
                label="black linegen ascii empty parens name",
            )
        elif "        \u00d8: Set[str] = set()\n" in text:
            text = replace_text_once(
                text,
                "        \u00d8: Set[str] = set()\n",
                replacement,
                label="black linegen ascii empty parens name",
            )
        elif replacement not in text:
            if "\u00d8" in text:
                raise RuntimeError("black linegen empty-parens anchor not found")
            return text
        updated = text.replace("parens=\u00d8", "parens=_empty_parens").replace(
            "keywords=\u00d8", "keywords=_empty_parens"
        )
        if "\u00d8" in updated:
            raise RuntimeError("black linegen empty-parens references were not fully patched")
        return updated

    transform_source_text(context, "Lib/black/linegen.py", patch_linegen, allow_missing=True)

    def patch_driver(text: str) -> str:
        if "from blib2to3._staticpython_grammars import GRAMMAR_TEXT as _STATICPYTHON_GRAMMAR_TEXT" not in text:
            text = replace_text_once(
                text,
                "# Pgen imports\n",
                "from blib2to3._staticpython_grammars import GRAMMAR_TEXT as _STATICPYTHON_GRAMMAR_TEXT\n\n# Pgen imports\n",
                label="blib2to3 driver static grammar import",
            )
        return replace_function_block_once(
            text,
            "load_packaged_grammar",
            "def load_packaged_grammar(package, grammar_source, cache_dir=None):\n"
            "    \"\"\"Normally, loads a pickled grammar by doing\n"
            "        pkgutil.get_data(package, pickled_grammar)\n"
            "    where *pickled_grammar* is computed from *grammar_source* by adding the\n"
            "    Python version and using a ``.pickle`` extension.\n\n"
            "    However, if *grammar_source* is an extant file, load_grammar(grammar_source)\n"
            "    is called instead. This facilitates using a packaged grammar file when needed\n"
            "    but preserves load_grammar's automatic regeneration behavior when possible.\n\n"
            "    \"\"\"\n"
            "    if os.path.isfile(grammar_source):\n"
            "        gp = _generate_pickle_name(grammar_source, cache_dir) if cache_dir else None\n"
            "        return load_grammar(grammar_source, gp=gp)\n"
            "    pickled_name = _generate_pickle_name(os.path.basename(grammar_source), cache_dir)\n"
            "    try:\n"
            "        data = pkgutil.get_data(package, pickled_name)\n"
            "    except FileNotFoundError:\n"
            "        data = None\n"
            "    if data is not None:\n"
            "        g = grammar.Grammar()\n"
            "        g.loads(data)\n"
            "        return g\n"
            "    grammar_name = os.path.basename(grammar_source)\n"
            "    grammar_data = _STATICPYTHON_GRAMMAR_TEXT.get(grammar_name)\n"
            "    if grammar_data is None:\n"
            "        raise FileNotFoundError(grammar_source)\n"
            "    stream = io.StringIO(grammar_data)\n"
            "    return pgen.ParserGenerator(grammar_source, stream=stream).make_grammar()\n",
            label="blib2to3 packaged grammar fallback",
            next_name="main",
        )

    transform_first_existing_source_text(
        context,
        ["Lib/blib2to3/pgen2/driver.py"],
        patch_driver,
        allow_all_missing=True,
    )

    def patch_schema(text: str) -> str:
        if 'fname = "black.schema.json"' not in text:
            if "black.schema.json" in text:
                raise RuntimeError("black schema embedded fallback anchor not found")
            return text
        text = replace_text_once(
            text,
            "from typing import Any\n",
            "from typing import Any\n\n"
            "try:\n"
            "    from black.resources._staticpython_schema import SCHEMA as _STATICPYTHON_SCHEMA\n"
            "except Exception:\n"
            "    _STATICPYTHON_SCHEMA = None\n",
            label="black schema static import",
        )
        return replace_text_once(
            text,
            "    fname = \"black.schema.json\"\n",
            "    fname = \"black.schema.json\"\n\n"
            "    if _STATICPYTHON_SCHEMA is not None:\n"
            "        return _STATICPYTHON_SCHEMA\n",
            label="black schema embedded fallback",
        )

    transform_source_text(context, "Lib/black/schema.py", patch_schema, allow_missing=True)


LIBRARY_INTEGRATION = LibraryIntegration(
    name="black",
    source_provider="pypi",
    project_name="black",
    dependencies=["aiohttp"],
    auto_resolve_dependencies=True,
    overlay_entries=[],
    materialized_paths=[
        "Lib/_black_version.py",
        "Lib/blib2to3/_staticpython_grammars.py",
    ],
    cleanup_paths=["Lib/_black_version.py"],
    python_packages=["_black_version", "black", "blackd", "blib2to3"],
    top_level_import_names=["black", "blackd", "blib2to3"],
    static_library_projects_release_x64=[],
    native_static_projects=[],
    builtin_module_registrations=[],
    staged_static_libraries_release_x64=[],
    python_link_dependencies_release_x64=[],
    python_link_wholearchive_release_x64=[],
    prepare_source_hooks=[prepare_black_source],
    pre_patch_hooks=[],
    post_patch_hooks=[patch_black_sources],
    pre_build_hooks=[],
)
