import json

from libs import replace_text_once, simple_library, source_path, transform_source_text, write_source_text


def patch_black_sources(context) -> None:
    grammar_text = {
        "Grammar.txt": source_path(context, "Lib/blib2to3/Grammar.txt").read_text(encoding="utf-8"),
        "PatternGrammar.txt": source_path(context, "Lib/blib2to3/PatternGrammar.txt").read_text(encoding="utf-8"),
    }
    schema = json.loads(source_path(context, "Lib/black/resources/black.schema.json").read_text(encoding="utf-8"))
    write_source_text(
        context,
        "Lib/blib2to3/_staticpython_grammars.py",
        "# Generated by StaticPython; keeps Black's blib2to3 grammars available after freezing.\n"
        f"GRAMMAR_TEXT = {grammar_text!r}\n",
    )
    write_source_text(
        context,
        "Lib/black/resources/_staticpython_schema.py",
        "# Generated by StaticPython; keeps Black's JSON schema available after freezing.\n"
        f"SCHEMA = {schema!r}\n",
    )

    def patch_linegen(text: str) -> str:
        replacement = "        _empty_parens: set[str] = set()\n"
        if "        \u00d8: set[str] = set()\n" in text:
            text = replace_text_once(
                text,
                "        \u00d8: set[str] = set()\n",
                replacement,
                label="black linegen ascii empty parens name",
            )
        elif "        \u00d8: Set[str] = set()\n" in text:
            text = replace_text_once(
                text,
                "        \u00d8: Set[str] = set()\n",
                replacement,
                label="black linegen ascii empty parens name",
            )
        elif replacement not in text:
            raise RuntimeError("expected snippet not found in black linegen ascii empty parens name")
        return text.replace("parens=\u00d8", "parens=_empty_parens").replace(
            "keywords=\u00d8", "keywords=_empty_parens"
        )

    transform_source_text(context, "Lib/black/linegen.py", patch_linegen)

    def patch_driver(text: str) -> str:
        text = replace_text_once(
            text,
            "import os\n",
            "import io\nimport os\n",
            label="blib2to3 driver io import",
        )
        text = replace_text_once(
            text,
            "# Pgen imports\n",
            "from blib2to3._staticpython_grammars import GRAMMAR_TEXT as _STATICPYTHON_GRAMMAR_TEXT\n\n# Pgen imports\n",
            label="blib2to3 driver static grammar import",
        )
        return replace_text_once(
            text,
            "    pickled_name = _generate_pickle_name(os.path.basename(grammar_source), cache_dir)\n"
            "    data = pkgutil.get_data(package, pickled_name)\n"
            "    assert data is not None\n"
            "    g = grammar.Grammar()\n"
            "    g.loads(data)\n"
            "    return g\n",
            "    pickled_name = _generate_pickle_name(os.path.basename(grammar_source), cache_dir)\n"
            "    try:\n"
            "        data = pkgutil.get_data(package, pickled_name)\n"
            "    except FileNotFoundError:\n"
            "        data = None\n"
            "    if data is not None:\n"
            "        g = grammar.Grammar()\n"
            "        g.loads(data)\n"
            "        return g\n"
            "    grammar_name = os.path.basename(grammar_source)\n"
            "    grammar_data = _STATICPYTHON_GRAMMAR_TEXT.get(grammar_name)\n"
            "    if grammar_data is None:\n"
            "        raise FileNotFoundError(grammar_source)\n"
            "    stream = io.StringIO(grammar_data)\n"
            "    return pgen.ParserGenerator(grammar_source, stream=stream).make_grammar()\n",
            label="blib2to3 packaged grammar fallback",
        )

    transform_source_text(context, "Lib/blib2to3/pgen2/driver.py", patch_driver)

    def patch_schema(text: str) -> str:
        text = replace_text_once(
            text,
            "from typing import Any\n",
            "from typing import Any\n\n"
            "try:\n"
            "    from black.resources._staticpython_schema import SCHEMA as _STATICPYTHON_SCHEMA\n"
            "except Exception:\n"
            "    _STATICPYTHON_SCHEMA = None\n",
            label="black schema static import",
        )
        return replace_text_once(
            text,
            "    fname = \"black.schema.json\"\n",
            "    fname = \"black.schema.json\"\n\n"
            "    if _STATICPYTHON_SCHEMA is not None:\n"
            "        return _STATICPYTHON_SCHEMA\n",
            label="black schema embedded fallback",
        )

    transform_source_text(context, "Lib/black/schema.py", patch_schema)


LIBRARY_INTEGRATION = simple_library(
    name="black",
    dependencies=["aiohttp"],
    source_mapping={
        "_black_version.py": "Lib/_black_version.py",
        "black": "Lib/black",
        "blackd": "Lib/blackd",
        "blib2to3": "Lib/blib2to3",
    },
    python_packages=["black", "blackd", "blib2to3"],
    materialized_paths=[
        "Lib/blib2to3/_staticpython_grammars.py",
        "Lib/black/resources/_staticpython_schema.py",
    ],
    post_patch_hooks=[patch_black_sources],
)
