from __future__ import annotations

import base64
import json

from libs import (
    inline_verification_step,
    pypi_library,
    replace_text_once,
    script_verification_step,
    source_path,
    transform_source_text,
    write_source_text,
)


def patch_jupyterlab_for_frozen_runtime(context) -> None:
    package_root = source_path(context, "Lib/jupyterlab")
    byte_resources = {
        path.relative_to(package_root).as_posix(): base64.b64encode(path.read_bytes()).decode("ascii")
        for root_name in ("static", "themes")
        for path in sorted((package_root / root_name).rglob("*"))
        if path.is_file()
    }
    templates = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted((package_root / "static").glob("*.html"))
    }
    static_package_data = json.loads((package_root / "static" / "package.json").read_text(encoding="utf-8"))
    core_package_data = json.loads((package_root / "staging" / "package.json").read_text(encoding="utf-8"))
    schemas: dict[str, dict] = {}
    for schema_path in sorted((package_root / "schemas").rglob("*.json")):
        if schema_path.name == "package.json.orig":
            continue
        rel_path = schema_path.relative_to(package_root / "schemas")
        package_dir = rel_path.parent.as_posix()
        plugin = schema_path.stem
        schema_name = f"{package_dir}:{plugin}"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        version = "N/A"
        package_json = schema_path.parent / "package.json.orig"
        if package_json.exists():
            version = json.loads(package_json.read_text(encoding="utf-8")).get("version", "N/A")
        schemas[schema_name] = {"schema": schema, "version": version}

    if "index.html" not in templates or "static/main.8d5c7fc83ea3808d9641.js" not in byte_resources:
        raise RuntimeError("expected JupyterLab static resources were not materialized")
    if "@jupyterlab/apputils-extension:themes" not in schemas:
        raise RuntimeError("expected JupyterLab theme settings schema was not materialized")

    write_source_text(
        context,
        "Lib/jupyterlab/_staticpython_resources.py",
        "# Generated by StaticPython; keeps JupyterLab package resources available after freezing.\n"
        "import base64\n\n"
        f"TEMPLATES = {templates!r}\n"
        f"BYTE_RESOURCES = {byte_resources!r}\n"
        f"STATIC_PACKAGE_DATA = {static_package_data!r}\n"
        f"CORE_PACKAGE_DATA = {core_package_data!r}\n"
        f"SCHEMAS = {schemas!r}\n\n"
        "def resource_bytes(path: str) -> bytes | None:\n"
        "    data = BYTE_RESOURCES.get(path.replace('\\\\', '/'))\n"
        "    return None if data is None else base64.b64decode(data)\n",
    )

    def patch_coreconfig(text: str) -> str:
        text = replace_text_once(
            text,
            "from .jlpmapp import HERE\n",
            "from .jlpmapp import HERE\nfrom ._staticpython_resources import CORE_PACKAGE_DATA as _STATICPYTHON_CORE_PACKAGE_DATA\n",
            label="jupyterlab coreconfig package data import",
        )
        return replace_text_once(
            text,
            "def _get_default_core_data():\n"
            "    \"\"\"Get the data for the app template.\"\"\"\n"
            "    with open(pjoin(HERE, \"staging\", \"package.json\")) as fid:\n"
            "        return json.load(fid)\n",
            "def _get_default_core_data():\n"
            "    \"\"\"Get the data for the app template.\"\"\"\n"
            "    if _STATICPYTHON_CORE_PACKAGE_DATA:\n"
            "        return json.loads(json.dumps(_STATICPYTHON_CORE_PACKAGE_DATA))\n"
            "    with open(pjoin(HERE, \"staging\", \"package.json\")) as fid:\n"
            "        return json.load(fid)\n",
            label="jupyterlab coreconfig embedded package data",
        )

    def patch_commands(text: str) -> str:
        text = replace_text_once(
            text,
            "from jupyterlab_server.config import (\n",
            "from jupyterlab._staticpython_resources import STATIC_PACKAGE_DATA as _STATICPYTHON_STATIC_PACKAGE_DATA\n"
            "from jupyterlab_server.config import (\n",
            label="jupyterlab commands static package data import",
        )
        text = replace_text_once(
            text,
            "def ensure_app(app_dir):\n"
            "    \"\"\"Ensure that an application directory is available.\n"
            "\n"
            "    If it does not exist, return a list of messages to prompt the user.\n"
            "    \"\"\"\n"
            "    if osp.exists(pjoin(app_dir, \"static\", \"index.html\")):\n"
            "        return\n",
            "def ensure_app(app_dir):\n"
            "    \"\"\"Ensure that an application directory is available.\n"
            "\n"
            "    If it does not exist, return a list of messages to prompt the user.\n"
            "    \"\"\"\n"
            "    if _STATICPYTHON_STATIC_PACKAGE_DATA or osp.exists(pjoin(app_dir, \"static\", \"index.html\")):\n"
            "        return\n",
            label="jupyterlab ensure_app embedded assets",
        )
        return replace_text_once(
            text,
            "def _get_static_data(app_dir):\n"
            "    \"\"\"Get the data for the app static dir.\"\"\"\n"
            "    target = pjoin(app_dir, \"static\", \"package.json\")\n"
            "    if osp.exists(target):\n"
            "        with open(target) as fid:\n"
            "            return json.load(fid)\n"
            "    else:\n"
            "        return None\n",
            "def _get_static_data(app_dir):\n"
            "    \"\"\"Get the data for the app static dir.\"\"\"\n"
            "    target = pjoin(app_dir, \"static\", \"package.json\")\n"
            "    if _STATICPYTHON_STATIC_PACKAGE_DATA:\n"
            "        return json.loads(json.dumps(_STATICPYTHON_STATIC_PACKAGE_DATA))\n"
            "    if osp.exists(target):\n"
            "        with open(target) as fid:\n"
            "            return json.load(fid)\n"
            "    else:\n"
            "        return None\n",
            label="jupyterlab static package data fallback",
        )

    def patch_extensions_init(text: str) -> str:
        manager_wrapper = """

class _StaticPythonEntryPoint:
    def __init__(self, factory):
        self._factory = factory

    def load(self):
        return self._factory
"""
        if "_StaticPythonEntryPoint" not in text:
            anchor = 'for entry in entry_points(group="jupyterlab.extension_manager_v1"):\n    MANAGERS[entry.name] = entry\n'
            text = replace_text_once(
                text,
                anchor,
                anchor + manager_wrapper,
                label="jupyterlab.extensions builtin manager wrapper",
            )

        registration = (
            '\nMANAGERS.setdefault("readonly", _StaticPythonEntryPoint(get_readonly_manager))\n'
            'MANAGERS.setdefault("pypi", _StaticPythonEntryPoint(get_pypi_manager))\n'
        )
        if 'MANAGERS.setdefault("readonly", _StaticPythonEntryPoint(get_readonly_manager))' not in text:
            anchor = (
                "def get_pypi_manager(\n"
                "    app_options: Optional[dict] = None,\n"
                "    ext_options: Optional[dict] = None,\n"
                "    parent: Optional[Configurable] = None,\n"
                ") -> ExtensionManager:\n"
                '    """PyPi Extension Manager factory"""\n'
                "    return PyPIExtensionManager(app_options, ext_options, parent)\n"
            )
            text = replace_text_once(
                text,
                anchor,
                anchor + registration,
                label="jupyterlab.extensions builtin manager registration",
            )
        return text

    def patch_labapp(text: str) -> str:
        old = (
            "            if entry_point is None:\n"
            '                self.log.error(f"Extension Manager: No manager defined for provider \'{provider}\'.")\n'
            "                raise NotImplementedError()\n"
            "            else:\n"
            '                self.log.info(f"Extension Manager is \'{provider}\'.")\n'
            "            manager_factory = entry_point.load()\n"
        )
        new = (
            "            if entry_point is None:\n"
            '                self.log.warning(\n'
            '                    f"Extension Manager provider \'{provider}\' is unavailable in this environment; "\n'
            '                    "falling back to read-only manager."\n'
            "                )\n"
            '                provider = "readonly"\n'
            "                manager_factory = ReadOnlyExtensionManager\n"
            "            else:\n"
            '                self.log.info(f"Extension Manager is \'{provider}\'.")\n'
            "                manager_factory = entry_point.load()\n"
        )
        return replace_text_once(text, old, new, label="jupyterlab.labapp extension manager fallback")

    transform_source_text(context, "Lib/jupyterlab/coreconfig.py", patch_coreconfig)
    transform_source_text(context, "Lib/jupyterlab/commands.py", patch_commands)
    transform_source_text(context, "Lib/jupyterlab/extensions/__init__.py", patch_extensions_init)
    transform_source_text(context, "Lib/jupyterlab/labapp.py", patch_labapp)


LIBRARY_INTEGRATION = pypi_library(
    name="jupyterlab",
    release_version="4.0.9",
    source_mapping={
        "jupyterlab": "Lib/jupyterlab",
        "jupyterlab/static": "share/jupyter/lab/static",
        "jupyterlab/schemas": "share/jupyter/lab/schemas",
        "jupyterlab/themes": "share/jupyter/lab/themes",
        "jupyterlab/staging": "share/jupyter/lab/staging",
        "jupyter-config/jupyter_server_config.d/jupyterlab.json": "etc/jupyter/jupyter_server_config.d/jupyterlab.json",
        "jupyter-config/jupyter_notebook_config.d/jupyterlab.json": "etc/jupyter/jupyter_notebook_config.d/jupyterlab.json",
    },
    cleanup_paths=[
        "etc/jupyter/jupyter_server_config.d/jupyterlab",
        "etc/jupyter/jupyter_notebook_config.d/jupyterlab",
    ],
    materialized_paths=[
        "share/jupyter/lab/static/index.html",
        "share/jupyter/lab/static/package.json",
        "share/jupyter/lab/schemas/@jupyterlab/apputils-extension/themes.json",
        "share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css",
        "share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.css",
        "share/jupyter/lab/staging/package.json",
        "etc/jupyter/jupyter_server_config.d/jupyterlab.json",
        "etc/jupyter/jupyter_notebook_config.d/jupyterlab.json",
        "Lib/jupyterlab/_staticpython_resources.py",
    ],
    verification_materialized_paths=[
        "Lib/jupyterlab",
        "share/jupyter/lab/static/index.html",
        "share/jupyter/lab/static/package.json",
        "share/jupyter/lab/schemas/@jupyterlab/apputils-extension/themes.json",
        "share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css",
        "share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.css",
        "share/jupyter/lab/staging/package.json",
        "etc/jupyter/jupyter_server_config.d/jupyterlab.json",
        "etc/jupyter/jupyter_notebook_config.d/jupyterlab.json",
    ],
    python_packages=["jupyterlab"],
    post_patch_hooks=[patch_jupyterlab_for_frozen_runtime],
    verification_steps=[
        inline_verification_step(
            "jupyterlab-smoke",
            """
import json
import os
import socket
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

from jupyterlab.commands import get_app_dir, get_user_settings_dir, get_workspaces_dir
from jupyterlab.coreconfig import CoreConfig
from jupyterlab.extensions import MANAGERS
from jupyterlab.labapp import LabApp
from jupyterlab_server.settings_utils import get_settings, get_settings_info

assert "readonly" in MANAGERS
assert "pypi" in MANAGERS

app_dir = Path(get_app_dir())
assert app_dir.name == "lab"
assert "user-settings" in get_user_settings_dir()
assert "workspaces" in get_workspaces_dir()

config = CoreConfig()
assert config.static_dir == "../static"
assert "@jupyterlab/application-extension" in config.extensions

app = LabApp()
assert app.default_url == "/lab"
assert Path(app.static_dir).name == "static"
assert Path(app.templates_dir).name == "static"
assert Path(app.schemas_dir).name == "schemas"
settings = get_settings(
    app.schemas_dir,
    app.settings_dir,
    "@jupyterlab/apputils-extension:themes",
    overrides={},
    labextensions_path=app.extra_labextensions_path + app.labextensions_path,
)
assert settings["id"] == "@jupyterlab/apputils-extension:themes"
assert "JupyterLab Theme" in settings["schema"]["title"]
settings_info = get_settings_info(
    app.schemas_dir,
    app.settings_dir,
    overrides={},
    labextensions_path=app.extra_labextensions_path + app.labextensions_path,
)
assert "@jupyterlab/apputils-extension:themes" in settings_info["settings"]


def reserve_port() -> int:
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.bind(("127.0.0.1", 0))
    try:
        return sock.getsockname()[1]
    finally:
        sock.close()


with tempfile.TemporaryDirectory() as temp_dir:
    temp_root = Path(temp_dir)
    work_dir = temp_root / "work"
    work_dir.mkdir()
    port = reserve_port()
    token = "staticpython-jupyterlab"
    env = os.environ.copy()
    env.update(
        {
            "JUPYTER_CONFIG_DIR": str(temp_root / "config"),
            "JUPYTER_DATA_DIR": str(temp_root / "data"),
            "JUPYTER_RUNTIME_DIR": str(temp_root / "runtime"),
            "JUPYTERLAB_SETTINGS_DIR": str(temp_root / "lab" / "user-settings"),
            "JUPYTERLAB_WORKSPACES_DIR": str(temp_root / "lab" / "workspaces"),
            "PYTHONUTF8": "1",
            "PYTHONIOENCODING": "utf-8",
        }
    )
    creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
    command = [
        sys.executable,
        "-m",
        "jupyterlab",
        "--ServerApp.ip=127.0.0.1",
        f"--ServerApp.port={port}",
        "--ServerApp.port_retries=0",
        "--ServerApp.open_browser=False",
        f"--ServerApp.root_dir={work_dir}",
        f"--ServerApp.token={token}",
        "--ServerApp.password=",
    ]
    process = subprocess.Popen(
        command,
        cwd=str(work_dir),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        encoding="utf-8",
        errors="replace",
        creationflags=creationflags,
    )
    output = ""
    try:
        url = f"http://127.0.0.1:{port}/lab?token={token}"
        response_text = None
        last_error = None
        deadline = time.time() + 90
        while time.time() < deadline:
            if process.poll() is not None:
                break
            try:
                with urllib.request.urlopen(url, timeout=5) as response:
                    response_text = response.read().decode("utf-8", errors="replace")
                    status_code = response.status
                break
            except Exception as exc:
                last_error = exc
                time.sleep(0.5)
        if response_text is None:
            if process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=15)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=15)
            if process.stdout is not None:
                output = process.stdout.read()
            raise AssertionError(
                f"failed to load /lab within timeout: {last_error!r}\\n"
                f"process return code: {process.returncode}\\n"
                f"jupyter output:\\n{output[-8000:]}"
            )
        assert status_code == 200
        assert "<title>JupyterLab</title>" in response_text
        assert "jupyter-config-data" in response_text
    finally:
        if process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=15)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait(timeout=15)
        if process.stdout is not None:
            output = process.stdout.read()
        if process.returncode not in (0, -15, 1):
            raise AssertionError(
                f"jupyterlab server exited unexpectedly with code {process.returncode}\\n"
                f"jupyter output:\\n{output[-8000:]}"
            )
""",
            timeout=180,
        ),
        script_verification_step(
            "jupyterlab-runtime",
            "scripts/jupyter_runtime.py",
            args=["--target", "lab"],
            timeout=180,
        ),
    ],
)
