from __future__ import annotations

import base64
import json

from libs import (
    pypi_library,
    replace_text_once,
    source_path,
    transform_source_text,
    write_source_text,
)


def patch_jupyterlab_for_frozen_runtime(context) -> None:
    package_root = source_path(context, "Lib/jupyterlab")
    byte_resources = {
        path.relative_to(package_root).as_posix(): base64.b64encode(path.read_bytes()).decode("ascii")
        for root_name in ("static", "themes")
        for path in sorted((package_root / root_name).rglob("*"))
        if path.is_file()
    }
    templates = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted((package_root / "static").glob("*.html"))
    }
    static_package_data = json.loads((package_root / "static" / "package.json").read_text(encoding="utf-8"))
    core_package_data = json.loads((package_root / "staging" / "package.json").read_text(encoding="utf-8"))
    schemas: dict[str, dict] = {}
    for schema_path in sorted((package_root / "schemas").rglob("*.json")):
        if schema_path.name == "package.json.orig":
            continue
        rel_path = schema_path.relative_to(package_root / "schemas")
        package_dir = rel_path.parent.as_posix()
        plugin = schema_path.stem
        schema_name = f"{package_dir}:{plugin}"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        version = "N/A"
        package_json = schema_path.parent / "package.json.orig"
        if package_json.exists():
            version = json.loads(package_json.read_text(encoding="utf-8")).get("version", "N/A")
        schemas[schema_name] = {"schema": schema, "version": version}

    if "index.html" not in templates or "static/main.8d5c7fc83ea3808d9641.js" not in byte_resources:
        raise RuntimeError("expected JupyterLab static resources were not materialized")
    if "@jupyterlab/apputils-extension:themes" not in schemas:
        raise RuntimeError("expected JupyterLab theme settings schema was not materialized")

    write_source_text(
        context,
        "Lib/jupyterlab/_staticpython_resources.py",
        "# Generated by StaticPython; keeps JupyterLab package resources available after freezing.\n"
        "import base64\n\n"
        f"TEMPLATES = {templates!r}\n"
        f"BYTE_RESOURCES = {byte_resources!r}\n"
        f"STATIC_PACKAGE_DATA = {static_package_data!r}\n"
        f"CORE_PACKAGE_DATA = {core_package_data!r}\n"
        f"SCHEMAS = {schemas!r}\n\n"
        "def resource_bytes(path: str) -> bytes | None:\n"
        "    data = BYTE_RESOURCES.get(path.replace('\\\\', '/'))\n"
        "    return None if data is None else base64.b64decode(data)\n",
    )

    def patch_coreconfig(text: str) -> str:
        text = replace_text_once(
            text,
            "from .jlpmapp import HERE\n",
            "from .jlpmapp import HERE\nfrom ._staticpython_resources import CORE_PACKAGE_DATA as _STATICPYTHON_CORE_PACKAGE_DATA\n",
            label="jupyterlab coreconfig package data import",
        )
        return replace_text_once(
            text,
            "def _get_default_core_data():\n"
            "    \"\"\"Get the data for the app template.\"\"\"\n"
            "    with open(pjoin(HERE, \"staging\", \"package.json\")) as fid:\n"
            "        return json.load(fid)\n",
            "def _get_default_core_data():\n"
            "    \"\"\"Get the data for the app template.\"\"\"\n"
            "    if _STATICPYTHON_CORE_PACKAGE_DATA:\n"
            "        return json.loads(json.dumps(_STATICPYTHON_CORE_PACKAGE_DATA))\n"
            "    with open(pjoin(HERE, \"staging\", \"package.json\")) as fid:\n"
            "        return json.load(fid)\n",
            label="jupyterlab coreconfig embedded package data",
        )

    def patch_commands(text: str) -> str:
        text = replace_text_once(
            text,
            "from jupyterlab_server.config import (\n",
            "from jupyterlab._staticpython_resources import STATIC_PACKAGE_DATA as _STATICPYTHON_STATIC_PACKAGE_DATA\n"
            "from jupyterlab_server.config import (\n",
            label="jupyterlab commands static package data import",
        )
        text = replace_text_once(
            text,
            "def ensure_app(app_dir):\n"
            "    \"\"\"Ensure that an application directory is available.\n"
            "\n"
            "    If it does not exist, return a list of messages to prompt the user.\n"
            "    \"\"\"\n"
            "    if osp.exists(pjoin(app_dir, \"static\", \"index.html\")):\n"
            "        return\n",
            "def ensure_app(app_dir):\n"
            "    \"\"\"Ensure that an application directory is available.\n"
            "\n"
            "    If it does not exist, return a list of messages to prompt the user.\n"
            "    \"\"\"\n"
            "    if _STATICPYTHON_STATIC_PACKAGE_DATA or osp.exists(pjoin(app_dir, \"static\", \"index.html\")):\n"
            "        return\n",
            label="jupyterlab ensure_app embedded assets",
        )
        return replace_text_once(
            text,
            "def _get_static_data(app_dir):\n"
            "    \"\"\"Get the data for the app static dir.\"\"\"\n"
            "    target = pjoin(app_dir, \"static\", \"package.json\")\n"
            "    if osp.exists(target):\n"
            "        with open(target) as fid:\n"
            "            return json.load(fid)\n"
            "    else:\n"
            "        return None\n",
            "def _get_static_data(app_dir):\n"
            "    \"\"\"Get the data for the app static dir.\"\"\"\n"
            "    target = pjoin(app_dir, \"static\", \"package.json\")\n"
            "    if _STATICPYTHON_STATIC_PACKAGE_DATA:\n"
            "        return json.loads(json.dumps(_STATICPYTHON_STATIC_PACKAGE_DATA))\n"
            "    if osp.exists(target):\n"
            "        with open(target) as fid:\n"
            "            return json.load(fid)\n"
            "    else:\n"
            "        return None\n",
            label="jupyterlab static package data fallback",
        )

    def patch_extensions_init(text: str) -> str:
        manager_wrapper = """

class _StaticPythonEntryPoint:
    def __init__(self, factory):
        self._factory = factory

    def load(self):
        return self._factory
"""
        if "_StaticPythonEntryPoint" not in text:
            anchor = 'for entry in entry_points(group="jupyterlab.extension_manager_v1"):\n    MANAGERS[entry.name] = entry\n'
            text = replace_text_once(
                text,
                anchor,
                anchor + manager_wrapper,
                label="jupyterlab.extensions builtin manager wrapper",
            )

        registration = (
            '\nMANAGERS.setdefault("readonly", _StaticPythonEntryPoint(get_readonly_manager))\n'
            'MANAGERS.setdefault("pypi", _StaticPythonEntryPoint(get_pypi_manager))\n'
        )
        if 'MANAGERS.setdefault("readonly", _StaticPythonEntryPoint(get_readonly_manager))' not in text:
            anchor = (
                "def get_pypi_manager(\n"
                "    app_options: Optional[dict] = None,\n"
                "    ext_options: Optional[dict] = None,\n"
                "    parent: Optional[Configurable] = None,\n"
                ") -> ExtensionManager:\n"
                '    """PyPi Extension Manager factory"""\n'
                "    return PyPIExtensionManager(app_options, ext_options, parent)\n"
            )
            text = replace_text_once(
                text,
                anchor,
                anchor + registration,
                label="jupyterlab.extensions builtin manager registration",
            )
        return text

    def patch_labapp(text: str) -> str:
        old = (
            "            if entry_point is None:\n"
            '                self.log.error(f"Extension Manager: No manager defined for provider \'{provider}\'.")\n'
            "                raise NotImplementedError()\n"
            "            else:\n"
            '                self.log.info(f"Extension Manager is \'{provider}\'.")\n'
            "            manager_factory = entry_point.load()\n"
        )
        new = (
            "            if entry_point is None:\n"
            '                self.log.warning(\n'
            '                    f"Extension Manager provider \'{provider}\' is unavailable in this environment; "\n'
            '                    "falling back to read-only manager."\n'
            "                )\n"
            '                provider = "readonly"\n'
            "                manager_factory = ReadOnlyExtensionManager\n"
            "            else:\n"
            '                self.log.info(f"Extension Manager is \'{provider}\'.")\n'
            "                manager_factory = entry_point.load()\n"
        )
        return replace_text_once(text, old, new, label="jupyterlab.labapp extension manager fallback")

    transform_source_text(context, "Lib/jupyterlab/coreconfig.py", patch_coreconfig)
    transform_source_text(context, "Lib/jupyterlab/commands.py", patch_commands)
    transform_source_text(context, "Lib/jupyterlab/extensions/__init__.py", patch_extensions_init)
    transform_source_text(context, "Lib/jupyterlab/labapp.py", patch_labapp)


LIBRARY_INTEGRATION = pypi_library(
    name="jupyterlab",
    release_version="4.0.9",
    source_mapping={
        "jupyterlab": "Lib/jupyterlab",
        "jupyterlab/static": "share/jupyter/lab/static",
        "jupyterlab/schemas": "share/jupyter/lab/schemas",
        "jupyterlab/themes": "share/jupyter/lab/themes",
        "jupyterlab/staging": "share/jupyter/lab/staging",
        "jupyter-config/jupyter_server_config.d/jupyterlab.json": "etc/jupyter/jupyter_server_config.d/jupyterlab.json",
        "jupyter-config/jupyter_notebook_config.d/jupyterlab.json": "etc/jupyter/jupyter_notebook_config.d/jupyterlab.json",
    },
    cleanup_paths=[
        "etc/jupyter/jupyter_server_config.d/jupyterlab",
        "etc/jupyter/jupyter_notebook_config.d/jupyterlab",
    ],
    materialized_paths=[
        "share/jupyter/lab/static/index.html",
        "share/jupyter/lab/static/package.json",
        "share/jupyter/lab/schemas/@jupyterlab/apputils-extension/themes.json",
        "share/jupyter/lab/themes/@jupyterlab/theme-light-extension/index.css",
        "share/jupyter/lab/themes/@jupyterlab/theme-dark-extension/index.css",
        "share/jupyter/lab/staging/package.json",
        "etc/jupyter/jupyter_server_config.d/jupyterlab.json",
        "etc/jupyter/jupyter_notebook_config.d/jupyterlab.json",
        "Lib/jupyterlab/_staticpython_resources.py",
    ],
    python_packages=["jupyterlab"],
    post_patch_hooks=[patch_jupyterlab_for_frozen_runtime],
)
