from __future__ import annotations

import base64

from libs import (
    inline_verification_step,
    pypi_library,
    replace_text_once,
    source_path,
    script_verification_step,
    transform_source_text,
    write_source_text,
)


def embed_jupyter_server_resources(context) -> None:
    package_root = source_path(context, "Lib/jupyter_server")
    text_resources = {
        path.relative_to(package_root / "templates").as_posix(): path.read_text(encoding="utf-8")
        for path in sorted((package_root / "templates").rglob("*"))
        if path.is_file()
    }
    byte_resources = {
        path.relative_to(package_root).as_posix(): base64.b64encode(path.read_bytes()).decode("ascii")
        for resource_dir in (package_root / "static", package_root / "event_schemas")
        for path in sorted(resource_dir.rglob("*"))
        if path.is_file()
    }
    if "main.html" not in text_resources or "static/style/index.css" not in byte_resources:
        raise RuntimeError("expected jupyter_server templates/static resources were not materialized")

    write_source_text(
        context,
        "Lib/jupyter_server/_staticpython_resources.py",
        "# Generated by StaticPython; keeps jupyter_server package resources available after freezing.\n"
        "import base64\n\n"
        f"TEMPLATES = {text_resources!r}\n"
        f"BYTE_RESOURCES = {byte_resources!r}\n\n"
        "def resource_bytes(path: str) -> bytes | None:\n"
        "    data = BYTE_RESOURCES.get(path.replace('\\\\', '/'))\n"
        "    return None if data is None else base64.b64decode(data)\n",
    )

    def patch_staticpython_resources(text: str) -> str:
        helper = r'''
"""StaticPython helpers for serving embedded Jupyter package resources."""

import importlib
from pathlib import PurePosixPath


RESOURCE_SCHEME = "staticpython-resource://"


def _normalize(path: str) -> str:
    return str(PurePosixPath(path.replace("\\", "/"))).lstrip("/")


def make_resource_path(package: str, key: str) -> str:
    return f"{RESOURCE_SCHEME}{package}/{_normalize(key)}"


def split_resource_path(path: str) -> tuple[str, str] | None:
    if not isinstance(path, str) or not path.startswith(RESOURCE_SCHEME):
        return None
    rest = path[len(RESOURCE_SCHEME) :]
    package, _, key = rest.partition("/")
    if not package or not key:
        return None
    return package, _normalize(key)


def resource_bytes_for_path(path: str) -> bytes | None:
    parsed = split_resource_path(path)
    if parsed is None:
        return None
    package, key = parsed
    try:
        module = importlib.import_module(f"{package}._staticpython_resources")
    except Exception:
        return None
    getter = getattr(module, "resource_bytes", None)
    if getter is None:
        resources = getattr(module, "BYTE_RESOURCES", {})
        data = resources.get(key)
        return data if isinstance(data, bytes) else None
    return getter(key)


def template_dict_for_package(package: str) -> dict[str, str]:
    try:
        module = importlib.import_module(f"{package}._staticpython_resources")
    except Exception:
        return {}
    return dict(getattr(module, "TEMPLATES", {}))


def resolve_resource_from_roots(roots, path: str) -> str | None:
    normalized_path = _normalize(path)
    if isinstance(roots, (str, bytes)):
        roots = [roots]
    for root in roots:
        root_text = str(root).replace("\\", "/").rstrip("/")
        probes: list[tuple[str, str]] = []
        if root_text.endswith("/jupyter_server/static"):
            probes.append(("jupyter_server", f"static/{normalized_path}"))
        if root_text.endswith("/jupyter_server/event_schemas"):
            probes.append(("jupyter_server", f"event_schemas/{normalized_path}"))
        if root_text.endswith("/notebook/static"):
            probes.append(("notebook", f"static/{normalized_path}"))
        if root_text.endswith("/jupyterlab/static") or root_text.endswith("/share/jupyter/lab/static"):
            probes.append(("jupyterlab", f"static/{normalized_path}"))
        if root_text.endswith("/jupyterlab/themes") or root_text.endswith("/share/jupyter/lab/themes"):
            probes.append(("jupyterlab", f"themes/{normalized_path}"))
        if root_text.endswith("/notebook/labextension") or root_text.endswith("/@jupyter-notebook/lab-extension"):
            probes.append(("notebook", f"labextension/{normalized_path}"))
        if root_text.endswith("/share/jupyter/labextensions") and normalized_path.startswith("@jupyter-notebook/lab-extension/"):
            probes.append(("notebook", "labextension/" + normalized_path.removeprefix("@jupyter-notebook/lab-extension/")))
        for package, key in probes:
            resource_path = make_resource_path(package, key)
            if resource_bytes_for_path(resource_path) is not None:
                return resource_path
    return None
'''
        return text + helper

    transform_source_text(
        context,
        "Lib/jupyter_server/_staticpython_resources.py",
        patch_staticpython_resources,
    )

    def patch_serverapp(text: str) -> str:
        text = replace_text_once(
            text,
            "from jinja2 import Environment, FileSystemLoader\n",
            "from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader\n"
            "from jupyter_server._staticpython_resources import template_dict_for_package as _staticpython_template_dict_for_package\n",
            label="jupyter_server serverapp jinja imports",
        )
        return replace_text_once(
            text,
            "        env = Environment(  # noqa[S701]\n"
            "            loader=FileSystemLoader(template_path), extensions=[\"jinja2.ext.i18n\"], **jenv_opt\n"
            "        )\n",
            "        env = Environment(  # noqa[S701]\n"
            "            loader=ChoiceLoader([\n"
            "                DictLoader(_staticpython_template_dict_for_package(\"jupyter_server\")),\n"
            "                FileSystemLoader(template_path),\n"
            "            ]),\n"
            "            extensions=[\"jinja2.ext.i18n\"],\n"
            "            **jenv_opt,\n"
            "        )\n",
            label="jupyter_server serverapp embedded template loader",
        )

    def patch_extension_application(text: str) -> str:
        text = replace_text_once(
            text,
            "from jinja2 import Environment, FileSystemLoader\n",
            "from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader\n"
            "from jupyter_server._staticpython_resources import template_dict_for_package as _staticpython_template_dict_for_package\n",
            label="jupyter_server extension application jinja imports",
        )
        return replace_text_once(
            text,
            "        self.jinja2_env = Environment(\n"
            "            loader=FileSystemLoader(self.template_paths),\n"
            "            extensions=[\"jinja2.ext.i18n\"],\n"
            "            autoescape=True,\n"
            "            **self.jinja2_options,\n"
            "        )\n",
            "        template_package = \"notebook\" if self.name == \"notebook\" else \"jupyterlab\" if self.name == \"lab\" else self.name\n"
            "        self.jinja2_env = Environment(\n"
            "            loader=ChoiceLoader([\n"
            "                DictLoader(_staticpython_template_dict_for_package(template_package)),\n"
            "                FileSystemLoader(self.template_paths),\n"
            "            ]),\n"
            "            extensions=[\"jinja2.ext.i18n\"],\n"
            "            autoescape=True,\n"
            "            **self.jinja2_options,\n"
            "        )\n",
            label="jupyter_server extension embedded template loader",
        )

    def patch_base_handlers(text: str) -> str:
        text = replace_text_once(
            text,
            "from jupyter_server.utils import (\n"
            "    ensure_async,\n"
            "    filefind,\n"
            "    url_escape,\n"
            "    url_is_absolute,\n"
            "    url_path_join,\n"
            "    urldecode_unix_socket_path,\n"
            ")\n",
            "from jupyter_server.utils import (\n"
            "    ensure_async,\n"
            "    filefind,\n"
            "    url_escape,\n"
            "    url_is_absolute,\n"
            "    url_path_join,\n"
            "    urldecode_unix_socket_path,\n"
            ")\n"
            "from jupyter_server._staticpython_resources import resource_bytes_for_path as _staticpython_resource_bytes_for_path\n"
            "from jupyter_server._staticpython_resources import resolve_resource_from_roots as _staticpython_resolve_resource_from_roots\n",
            label="jupyter_server base handlers resource imports",
        )
        text = replace_text_once(
            text,
            "    @classmethod\n"
            "    def get_absolute_path(cls, roots, path):\n"
            "        \"\"\"locate a file to serve on our static file search path\"\"\"\n"
            "        with cls._lock:\n"
            "            if path in cls._static_paths:\n"
            "                return cls._static_paths[path]\n"
            "            try:\n"
            "                abspath = os.path.abspath(filefind(path, roots))\n"
            "            except OSError:\n"
            "                # IOError means not found\n"
            "                return \"\"\n"
            "\n"
            "            cls._static_paths[path] = abspath\n"
            "\n"
            "            log().debug(f\"Path {path} served from {abspath}\")\n"
            "            return abspath\n",
            "    @classmethod\n"
            "    def get_absolute_path(cls, roots, path):\n"
            "        \"\"\"locate a file to serve on our static file search path\"\"\"\n"
            "        cache_key = (tuple(roots) if isinstance(roots, list) else roots, path)\n"
            "        with cls._lock:\n"
            "            if cache_key in cls._static_paths:\n"
            "                return cls._static_paths[cache_key]\n"
            "            try:\n"
            "                abspath = os.path.abspath(filefind(path, roots))\n"
            "            except OSError:\n"
            "                abspath = _staticpython_resolve_resource_from_roots(roots, path) or \"\"\n"
            "\n"
            "            cls._static_paths[cache_key] = abspath\n"
            "\n"
            "            log().debug(f\"Path {path} served from {abspath}\")\n"
            "            return abspath\n",
            label="jupyter_server filefind embedded resource lookup",
        )
        text = replace_text_once(
            text,
            "    def validate_absolute_path(self, root, absolute_path):\n"
            "        \"\"\"check if the file should be served (raises 404, 403, etc.)\"\"\"\n"
            "        if not absolute_path:\n"
            "            raise web.HTTPError(404)\n"
            "\n"
            "        for root in self.root:\n"
            "            if (absolute_path + os.sep).startswith(root):\n"
            "                break\n"
            "\n"
            "        return super().validate_absolute_path(root, absolute_path)\n",
            "    def validate_absolute_path(self, root, absolute_path):\n"
            "        \"\"\"check if the file should be served (raises 404, 403, etc.)\"\"\"\n"
            "        if not absolute_path:\n"
            "            raise web.HTTPError(404)\n"
            "        if _staticpython_resource_bytes_for_path(absolute_path) is not None:\n"
            "            return absolute_path\n"
            "\n"
            "        for root in self.root:\n"
            "            if (absolute_path + os.sep).startswith(root):\n"
            "                break\n"
            "\n"
            "        return super().validate_absolute_path(root, absolute_path)\n",
            label="jupyter_server filefind embedded resource validation",
        )
        addition = (
            "    @classmethod\n"
            "    def get_content(cls, abspath, start=None, end=None):\n"
            "        data = _staticpython_resource_bytes_for_path(abspath)\n"
            "        if data is not None:\n"
            "            if start is not None or end is not None:\n"
            "                data = data[start:end]\n"
            "            yield data\n"
            "            return\n"
            "        yield from super().get_content(abspath, start, end)\n"
            "\n"
            "    def get_content_size(self):\n"
            "        assert self.absolute_path is not None\n"
            "        data = _staticpython_resource_bytes_for_path(self.absolute_path)\n"
            "        if data is not None:\n"
            "            return len(data)\n"
            "        return super().get_content_size()\n"
            "\n"
            "    def get_modified_time(self):\n"
            "        assert self.absolute_path is not None\n"
            "        if _staticpython_resource_bytes_for_path(self.absolute_path) is not None:\n"
            "            return None\n"
            "        return super().get_modified_time()\n"
            "\n"
        )
        if "def get_content(cls, abspath, start=None, end=None):\n        data = _staticpython_resource_bytes_for_path" not in text:
            text = replace_text_once(
                text,
                "    def validate_absolute_path(self, root, absolute_path):\n"
                "        \"\"\"check if the file should be served (raises 404, 403, etc.)\"\"\"\n"
                "        if not absolute_path:\n"
                "            raise web.HTTPError(404)\n"
                "        if _staticpython_resource_bytes_for_path(absolute_path) is not None:\n"
                "            return absolute_path\n"
                "\n"
                "        for root in self.root:\n"
                "            if (absolute_path + os.sep).startswith(root):\n"
                "                break\n"
                "\n"
                "        return super().validate_absolute_path(root, absolute_path)\n",
                "    def validate_absolute_path(self, root, absolute_path):\n"
                "        \"\"\"check if the file should be served (raises 404, 403, etc.)\"\"\"\n"
                "        if not absolute_path:\n"
                "            raise web.HTTPError(404)\n"
                "        if _staticpython_resource_bytes_for_path(absolute_path) is not None:\n"
                "            return absolute_path\n"
                "\n"
                "        for root in self.root:\n"
                "            if (absolute_path + os.sep).startswith(root):\n"
                "                break\n"
                "\n"
                "        return super().validate_absolute_path(root, absolute_path)\n"
                "\n"
                + addition,
                label="jupyter_server filefind embedded resource methods",
            )
        return text

    transform_source_text(context, "Lib/jupyter_server/serverapp.py", patch_serverapp)
    transform_source_text(context, "Lib/jupyter_server/extension/application.py", patch_extension_application)
    transform_source_text(context, "Lib/jupyter_server/base/handlers.py", patch_base_handlers)


LIBRARY_INTEGRATION = pypi_library(
    name="jupyter_server",
    project_name="jupyter-server",
    release_version="2.7.0",
    source_mapping={
        "jupyter_server": "Lib/jupyter_server",
    },
    materialized_paths=[
        "Lib/jupyter_server/templates/404.html",
        "Lib/jupyter_server/templates/browser-open.html",
        "Lib/jupyter_server/templates/login.html",
        "Lib/jupyter_server/templates/logout.html",
        "Lib/jupyter_server/templates/page.html",
        "Lib/jupyter_server/templates/error.html",
        "Lib/jupyter_server/templates/view.html",
        "Lib/jupyter_server/templates/main.html",
        "Lib/jupyter_server/event_schemas/contents_service/v1.yaml",
        "Lib/jupyter_server/_staticpython_resources.py",
    ],
    verification_materialized_paths=[
        "Lib/jupyter_server/templates/404.html",
        "Lib/jupyter_server/templates/browser-open.html",
        "Lib/jupyter_server/templates/login.html",
        "Lib/jupyter_server/templates/logout.html",
        "Lib/jupyter_server/templates/page.html",
        "Lib/jupyter_server/templates/error.html",
        "Lib/jupyter_server/templates/view.html",
        "Lib/jupyter_server/templates/main.html",
        "Lib/jupyter_server/static/style/index.css",
        "Lib/jupyter_server/event_schemas/contents_service/v1.yaml",
    ],
    python_packages=["jupyter_server"],
    verification_imports=["jupyter_server.serverapp"],
    post_patch_hooks=[embed_jupyter_server_resources],
    verification_steps=[
        inline_verification_step(
            "jupyter-server-smoke",
            """
from pathlib import Path
from types import SimpleNamespace

import jupyter_server
from jupyter_server.base.handlers import AuthenticatedHandler
from jupyter_server.extension.application import ExtensionApp
from jupyter_server.serverapp import ServerApp
from jupyter_server.utils import url_path_join

template_roots = [Path(path) for path in jupyter_server.DEFAULT_TEMPLATE_PATH_LIST]

assert Path(jupyter_server.DEFAULT_STATIC_FILES_PATH).name == "static"
assert Path(jupyter_server.DEFAULT_EVENTS_SCHEMA_PATH).name == "event_schemas"
assert any(path.name == "templates" for path in template_roots)
assert url_path_join("/base/", "api", "status") == "/base/api/status"

app = ServerApp()
assert app.default_url == "/"
assert app.contents_manager_class is not None
app.gateway_config = SimpleNamespace(gateway_enabled=False)
assert app.kernel_manager_class is not None
assert app.session_manager_class is not None
assert app.kernel_spec_manager_class is not None
assert app.kernel_websocket_connection_class is not None
assert any(Path(path).name == "static" for path in app.static_file_path)
assert issubclass(ExtensionApp, object)
assert callable(AuthenticatedHandler.set_default_headers)
""",
            timeout=300,
        ),
        script_verification_step(
            "jupyter-server-runtime",
            "scripts/jupyter_runtime.py",
            args=["--target", "server"],
            timeout=180,
        ),
    ],
)
