from __future__ import annotations

import base64
import re

from libs import (
    pypi_library,
    replace_function_block_once,
    replace_regex_once,
    replace_text_once,
    source_path,
    transform_source_text,
    write_source_text,
)


def embed_jupyter_server_resources(context) -> None:
    package_root = source_path(context, "Lib/jupyter_server")
    serverapp_path = package_root / "serverapp.py"
    extension_application_path = package_root / "extension" / "application.py"
    base_handlers_path = package_root / "base" / "handlers.py"
    templates_root = package_root / "templates"
    if templates_root.exists():
        text_resources = {
            path.relative_to(templates_root).as_posix(): path.read_text(encoding="utf-8")
            for path in sorted(templates_root.rglob("*"))
            if path.is_file()
        }
    else:
        legacy_template_files = [
            path
            for path in sorted(package_root.glob("*.html"))
            if path.is_file()
        ]
        text_resources = {
            path.name: path.read_text(encoding="utf-8")
            for path in legacy_template_files
        }
    byte_resources = {
        path.relative_to(package_root).as_posix(): base64.b64encode(path.read_bytes()).decode("ascii")
        for resource_dir in (package_root / "static", package_root / "event_schemas")
        if resource_dir.exists()
        for path in sorted(resource_dir.rglob("*"))
        if path.is_file()
    }
    has_event_schema_resources = any(path.startswith("event_schemas/") for path in byte_resources)

    write_source_text(
        context,
        "Lib/jupyter_server/_staticpython_resources.py",
        "# Generated by StaticPython; keeps jupyter_server package resources available after freezing.\n"
        "import base64\n\n"
        f"TEMPLATES = {text_resources!r}\n"
        f"BYTE_RESOURCES = {byte_resources!r}\n\n"
        "def resource_bytes(path: str) -> bytes | None:\n"
        "    data = BYTE_RESOURCES.get(path.replace('\\\\', '/'))\n"
        "    return None if data is None else base64.b64decode(data)\n",
    )
    if not text_resources and not byte_resources:
        return

    def patch_staticpython_resources(text: str) -> str:
        helper = r'''
"""StaticPython helpers for serving embedded Jupyter package resources."""

import importlib
from pathlib import PurePosixPath


RESOURCE_SCHEME = "staticpython-resource://"


def _normalize(path: str) -> str:
    return str(PurePosixPath(path.replace("\\", "/"))).lstrip("/")


def make_resource_path(package: str, key: str) -> str:
    return f"{RESOURCE_SCHEME}{package}/{_normalize(key)}"


def split_resource_path(path: str) -> tuple[str, str] | None:
    if not isinstance(path, str) or not path.startswith(RESOURCE_SCHEME):
        return None
    rest = path[len(RESOURCE_SCHEME) :]
    package, _, key = rest.partition("/")
    if not package or not key:
        return None
    return package, _normalize(key)


def resource_bytes_for_path(path: str) -> bytes | None:
    parsed = split_resource_path(path)
    if parsed is None:
        return None
    package, key = parsed
    try:
        module = importlib.import_module(f"{package}._staticpython_resources")
    except Exception:
        return None
    getter = getattr(module, "resource_bytes", None)
    if getter is None:
        resources = getattr(module, "BYTE_RESOURCES", {})
        data = resources.get(key)
        return data if isinstance(data, bytes) else None
    return getter(key)


def template_dict_for_package(package: str) -> dict[str, str]:
    try:
        module = importlib.import_module(f"{package}._staticpython_resources")
    except Exception:
        return {}
    return dict(getattr(module, "TEMPLATES", {}))


def resource_text(package: str, key: str, encoding: str = "utf-8") -> str | None:
    resource_path = make_resource_path(package, key)
    data = resource_bytes_for_path(resource_path)
    return None if data is None else data.decode(encoding)


def resolve_resource_from_roots(roots, path: str) -> str | None:
    normalized_path = _normalize(path)
    if isinstance(roots, (str, bytes)):
        roots = [roots]
    for root in roots:
        root_text = str(root).replace("\\", "/").rstrip("/")
        probes: list[tuple[str, str]] = []
        if root_text.endswith("/jupyter_server/static"):
            probes.append(("jupyter_server", f"static/{normalized_path}"))
        if root_text.endswith("/jupyter_server/event_schemas"):
            probes.append(("jupyter_server", f"event_schemas/{normalized_path}"))
        if root_text.endswith("/notebook/static"):
            probes.append(("notebook", f"static/{normalized_path}"))
        if root_text.endswith("/jupyterlab/static") or root_text.endswith("/share/jupyter/lab/static"):
            probes.append(("jupyterlab", f"static/{normalized_path}"))
        if root_text.endswith("/jupyterlab/themes") or root_text.endswith("/share/jupyter/lab/themes"):
            probes.append(("jupyterlab", f"themes/{normalized_path}"))
        if root_text.endswith("/notebook/labextension") or root_text.endswith("/@jupyter-notebook/lab-extension"):
            probes.append(("notebook", f"labextension/{normalized_path}"))
        if root_text.endswith("/share/jupyter/labextensions") and normalized_path.startswith("@jupyter-notebook/lab-extension/"):
            probes.append(("notebook", "labextension/" + normalized_path.removeprefix("@jupyter-notebook/lab-extension/")))
        for package, key in probes:
            resource_path = make_resource_path(package, key)
            if resource_bytes_for_path(resource_path) is not None:
                return resource_path
    return None
'''
        return text + helper

    transform_source_text(
        context,
        "Lib/jupyter_server/_staticpython_resources.py",
        patch_staticpython_resources,
    )

    def patch_serverapp(text: str) -> str:
        if "_staticpython_template_dict_for_package" not in text:
            if "from jinja2 import Environment, FileSystemLoader\n" in text:
                text = replace_text_once(
                    text,
                    "from jinja2 import Environment, FileSystemLoader\n",
                    "from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader\n"
                    "from jupyter_server._staticpython_resources import resource_text as _staticpython_resource_text\n"
                    "from jupyter_server._staticpython_resources import template_dict_for_package as _staticpython_template_dict_for_package\n",
                    label="jupyter_server serverapp jinja imports",
                )
            else:
                text = replace_regex_once(
                    text,
                    r"(?m)^from jinja2 import ([^\n]+)\n",
                    "from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader\n"
                    "from jupyter_server._staticpython_resources import resource_text as _staticpython_resource_text\n"
                    "from jupyter_server._staticpython_resources import template_dict_for_package as _staticpython_template_dict_for_package\n",
                    label="jupyter_server serverapp jinja imports",
                )
        if "ChoiceLoader([" not in text and "FileSystemLoader(template_path)" in text:
            exact_loader_block = (
                "        env = Environment(  # noqa[S701]\n"
                "            loader=FileSystemLoader(template_path), extensions=[\"jinja2.ext.i18n\"], **jenv_opt\n"
                "        )\n"
            )
            replacement_loader_block = (
                "        env = Environment(  # noqa[S701]\n"
                "            loader=ChoiceLoader([\n"
                "                DictLoader(_staticpython_template_dict_for_package(\"jupyter_server\")),\n"
                "                FileSystemLoader(template_path),\n"
                "            ]),\n"
                "            extensions=[\"jinja2.ext.i18n\"],\n"
                "            **jenv_opt,\n"
                "        )\n"
            )
            if exact_loader_block in text:
                text = replace_text_once(
                    text,
                    exact_loader_block,
                    replacement_loader_block,
                    label="jupyter_server serverapp embedded template loader",
                )
            else:
                text = replace_regex_once(
                    text,
                    r"(?m)^        env = Environment\([^\n]*\n"
                    r"^            loader=FileSystemLoader\(template_path\), extensions=\[(?:'|\")jinja2\.ext\.i18n(?:'|\")\], \*\*jenv_opt\s*\n"
                    r"^        \)\n",
                    replacement_loader_block,
                    label="jupyter_server serverapp embedded template loader",
                    flags=re.MULTILINE,
                )
        if (
            has_event_schema_resources
            and "register_event_schema(schema_text if schema_text is not None else schema_path)" not in text
        ):
            exact_schema_block = (
                "            schema_path = DEFAULT_EVENTS_SCHEMA_PATH / rel_schema_path\n"
                "            # Use this pathlib object to register the schema\n"
                "            self.event_logger.register_event_schema(schema_path)\n"
            )
            replacement_schema_block = (
                "            schema_text = _staticpython_resource_text(\"jupyter_server\", f\"event_schemas/{rel_schema_path}\")\n"
                "            schema_path = DEFAULT_EVENTS_SCHEMA_PATH / rel_schema_path\n"
                "            self.event_logger.register_event_schema(schema_text if schema_text is not None else schema_path)\n"
            )
            if exact_schema_block in text:
                text = replace_text_once(
                    text,
                    exact_schema_block,
                    replacement_schema_block,
                    label="jupyter_server embedded event schema registration",
                )
            else:
                text = replace_regex_once(
                    text,
                    r"(?m)^            schema_path = DEFAULT_EVENTS_SCHEMA_PATH / rel_schema_path\n"
                    r"(?:            #.*\n)*"
                    r"            self\.event_logger\.register_event_schema\(schema_path\)\n",
                    replacement_schema_block,
                    label="jupyter_server embedded event schema registration",
                    flags=re.MULTILINE,
                )
        return text

    def patch_extension_application(text: str) -> str:
        if "_staticpython_template_dict_for_package" not in text:
            text = replace_regex_once(
                text,
                r"(?m)^from jinja2 import ([^\n]+)\n",
                "from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader\n"
                "from jupyter_server._staticpython_resources import template_dict_for_package as _staticpython_template_dict_for_package\n",
                label="jupyter_server extension application jinja imports",
            )
        if "ChoiceLoader([" in text:
            return text
        return replace_regex_once(
            text,
            r"(?ms)^(\s*)self\.jinja2_env = Environment\(\s*loader=FileSystemLoader\(self\.template_paths\),\s*extensions=\[(?:'|\")jinja2\.ext\.i18n(?:'|\")\],\s*autoescape=True,\s*\*\*self\.jinja2_options,\s*\)\n",
            "        template_package = \"notebook\" if self.name == \"notebook\" else \"jupyterlab\" if self.name == \"lab\" else self.name\n"
            "        self.jinja2_env = Environment(\n"
            "            loader=ChoiceLoader([\n"
            "                DictLoader(_staticpython_template_dict_for_package(template_package)),\n"
            "                FileSystemLoader(self.template_paths),\n"
            "            ]),\n"
            "            extensions=[\"jinja2.ext.i18n\"],\n"
            "            autoescape=True,\n"
            "            **self.jinja2_options,\n"
            "        )\n",
            label="jupyter_server extension embedded template loader",
        )

    def patch_base_handlers(text: str) -> str:
        if "_staticpython_resource_bytes_for_path" not in text:
            helper_imports = (
                "from jupyter_server._staticpython_resources import resource_bytes_for_path as _staticpython_resource_bytes_for_path\n"
                "from jupyter_server._staticpython_resources import resolve_resource_from_roots as _staticpython_resolve_resource_from_roots\n"
            )
            match = re.search(
                r"(?ms)^from jupyter_server\.utils import \(\n.*?^\)\n",
                text,
            )
            if match is None:
                match = re.search(
                    r"(?m)^(?:from jupyter_server\.utils import [^\n]+\n)+",
                    text,
                )
            if match is None:
                match = re.search(
                    r"(?m)^(?:from jupyter_server(?:\.[^\s]+)? import [^\n]+\n|import jupyter_server\n)+",
                    text,
                )
            if match is None:
                raise RuntimeError("expected snippet not found in jupyter_server base handlers resource imports")
            text = (
                text[: match.end()]
                + helper_imports
                + text[match.end() :]
            )
        class_start = text.find("class FileFindHandler(")
        if class_start == -1:
            raise RuntimeError("expected snippet not found in jupyter_server FileFindHandler class")
        class_end = text.find("\n\nclass ", class_start)
        if class_end == -1:
            class_end = len(text)
        class_block = text[class_start:class_end]
        get_absolute_path_block = (
            "    def get_absolute_path(cls, roots, path):\n"
            "        \"\"\"locate a file to serve on our static file search path\"\"\"\n"
            "        with cls._lock:\n"
            "            if path in cls._static_paths:\n"
            "                return cls._static_paths[path]\n"
            "            try:\n"
            "                abspath = os.path.abspath(filefind(path, roots))\n"
            "            except OSError:\n"
            "                abspath = _staticpython_resolve_resource_from_roots(roots, path) or \"\"\n"
            "\n"
            "            cls._static_paths[path] = abspath\n"
            "\n"
            "            log().debug(f\"Path {path} served from {abspath}\")\n"
            "            return abspath\n"
            "\n"
        )
        class_block = replace_function_block_once(
            class_block,
            "get_absolute_path",
            get_absolute_path_block,
            label="jupyter_server filefind embedded resource lookup",
            next_name="validate_absolute_path",
        )
        validate_absolute_path_block = (
            "    def validate_absolute_path(self, root, absolute_path):\n"
            "        \"\"\"check if the file should be served (raises 404, 403, etc.)\"\"\"\n"
            "        if not absolute_path:\n"
            "            raise web.HTTPError(404)\n"
            "        if _staticpython_resource_bytes_for_path(absolute_path) is not None:\n"
            "            return absolute_path\n"
            "\n"
            "        selected_root = root\n"
            "        if isinstance(selected_root, (list, tuple)):\n"
            "            selected_root = next((entry for entry in selected_root if isinstance(entry, (str, bytes, os.PathLike))), None)\n"
            "        if selected_root is None:\n"
            "            for candidate_root in self.root:\n"
            "                if isinstance(candidate_root, (str, bytes, os.PathLike)) and (absolute_path + os.sep).startswith(str(candidate_root)):\n"
            "                    selected_root = candidate_root\n"
            "                    break\n"
            "        if selected_root is None:\n"
            "            raise web.HTTPError(404)\n"
            "        return super().validate_absolute_path(selected_root, absolute_path)\n"
            "\n"
            "    @classmethod\n"
            "    def get_content(cls, abspath, start=None, end=None):\n"
            "        data = _staticpython_resource_bytes_for_path(abspath)\n"
            "        if data is not None:\n"
            "            if start is not None or end is not None:\n"
            "                data = data[start:end]\n"
            "            yield data\n"
            "            return\n"
            "        yield from super().get_content(abspath, start, end)\n"
            "\n"
            "    def get_content_size(self):\n"
            "        assert self.absolute_path is not None\n"
            "        data = _staticpython_resource_bytes_for_path(self.absolute_path)\n"
            "        if data is not None:\n"
            "            return len(data)\n"
            "        return super().get_content_size()\n"
            "\n"
            "    def get_modified_time(self):\n"
            "        assert self.absolute_path is not None\n"
            "        if _staticpython_resource_bytes_for_path(self.absolute_path) is not None:\n"
            "            return None\n"
            "        return super().get_modified_time()\n"
            "\n"
        )
        class_block = replace_function_block_once(
            class_block,
            "validate_absolute_path",
            validate_absolute_path_block,
            label="jupyter_server filefind embedded resource validation",
        )
        text = text[:class_start] + class_block + text[class_end:]
        return text

    if serverapp_path.exists():
        transform_source_text(context, "Lib/jupyter_server/serverapp.py", patch_serverapp)
    if extension_application_path.exists():
        transform_source_text(context, "Lib/jupyter_server/extension/application.py", patch_extension_application)
    if base_handlers_path.exists() and byte_resources:
        transform_source_text(context, "Lib/jupyter_server/base/handlers.py", patch_base_handlers)


LIBRARY_INTEGRATION = pypi_library(
    name="jupyter_server",
    project_name="jupyter-server",
    release_version="2.7.0",
    source_mapping={
        "jupyter_server": "Lib/jupyter_server",
    },
    materialized_paths=[
        "Lib/jupyter_server/_staticpython_resources.py",
    ],
    python_packages=["jupyter_server"],
    post_patch_hooks=[embed_jupyter_server_resources],
)
