from __future__ import annotations

import base64
import json

from libs import pypi_library, source_path, write_source_text


def embed_notebook_resources(context) -> None:
    package_root = source_path(context, "Lib/notebook")
    templates = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted((package_root / "templates").glob("*.html"))
    }
    byte_resources = {
        path.relative_to(package_root).as_posix(): base64.b64encode(path.read_bytes()).decode("ascii")
        for root_name in ("static", "labextension")
        for path in sorted((package_root / root_name).rglob("*"))
        if path.is_file()
    }
    labextension_package = json.loads((package_root / "labextension" / "package.json").read_text(encoding="utf-8"))
    labextension_schemas: dict[str, dict] = {}
    for schema_path in sorted((package_root / "labextension" / "schemas").rglob("*.json")):
        if schema_path.name == "package.json.orig":
            continue
        rel_path = schema_path.relative_to(package_root / "labextension" / "schemas")
        package_dir = rel_path.parent.as_posix()
        plugin = schema_path.stem
        schema_name = f"{package_dir}:{plugin}"
        schema = json.loads(schema_path.read_text(encoding="utf-8"))
        version = "N/A"
        package_json = schema_path.parent / "package.json.orig"
        if package_json.exists():
            version = json.loads(package_json.read_text(encoding="utf-8")).get("version", "N/A")
        labextension_schemas[schema_name] = {"schema": schema, "version": version}
    if "tree.html" not in templates or "static/bundle.js" not in byte_resources:
        raise RuntimeError("expected Notebook templates/static resources were not materialized")
    if "labextension/package.json" not in byte_resources:
        raise RuntimeError("expected Notebook labextension resources were not materialized")

    write_source_text(
        context,
        "Lib/notebook/_staticpython_resources.py",
        "# Generated by StaticPython; keeps Notebook package resources available after freezing.\n"
        "import base64\n\n"
        f"TEMPLATES = {templates!r}\n"
        f"BYTE_RESOURCES = {byte_resources!r}\n"
        f"LABEXTENSION_PACKAGE = {labextension_package!r}\n"
        f"LABEXTENSION_SCHEMAS = {labextension_schemas!r}\n"
        "FEDERATED_EXTENSIONS = [\n"
        "    {\n"
        "        \"package\": LABEXTENSION_PACKAGE,\n"
        "        \"ext_dir\": \"staticpython-resource://notebook/labextension\",\n"
        "        \"ext_path\": \"staticpython-resource://notebook/labextension\",\n"
        "    }\n"
        "]\n\n"
        "def resource_bytes(path: str) -> bytes | None:\n"
        "    data = BYTE_RESOURCES.get(path.replace('\\\\', '/'))\n"
        "    return None if data is None else base64.b64decode(data)\n",
    )


LIBRARY_INTEGRATION = pypi_library(
    name="notebook",
    release_version="7.0.8",
    source_mapping={
        "notebook": "Lib/notebook",
        "notebook/labextension": "share/jupyter/labextensions/@jupyter-notebook/lab-extension",
        "jupyter-config/jupyter_server_config.d/notebook.json": "etc/jupyter/jupyter_server_config.d/notebook.json",
    },
    cleanup_paths=[
        "etc/jupyter/jupyter_server_config.d/notebook",
    ],
    materialized_paths=[
        "Lib/notebook/templates/error.html",
        "Lib/notebook/templates/consoles.html",
        "Lib/notebook/templates/edit.html",
        "Lib/notebook/templates/notebooks.html",
        "Lib/notebook/templates/terminals.html",
        "Lib/notebook/templates/tree.html",
        "Lib/notebook/static/bundle.js",
        "Lib/notebook/_staticpython_resources.py",
        "share/jupyter/labextensions/@jupyter-notebook/lab-extension/package.json",
        "etc/jupyter/jupyter_server_config.d/notebook.json",
    ],
    python_packages=["notebook"],
    post_patch_hooks=[embed_notebook_resources],
)
