from __future__ import annotations

import json

from libs import inline_verification_step, replace_text_once, simple_library, source_path, transform_source_text, write_source_text


def embed_nbformat_schemas(context) -> None:
    schemas = {}
    for path in sorted(source_path(context, "Lib/nbformat").rglob("*.json")):
        schemas[path.name] = json.loads(path.read_text(encoding="utf-8"))

    write_source_text(
        context,
        "Lib/nbformat/_static_schemas.py",
        "# Generated by StaticPython; keeps nbformat validation usable after freezing.\n"
        + "SCHEMAS = "
        + repr(schemas)
        + "\n",
    )

    def patch_validator(text: str) -> str:
        text = replace_text_once(
            text,
            "from .warnings import DuplicateCellId, MissingIDFieldWarning\n",
            "from .warnings import DuplicateCellId, MissingIDFieldWarning\nfrom ._static_schemas import SCHEMAS as _STATICPYTHON_SCHEMAS\n",
            label="nbformat static schema import",
        )
        return replace_text_once(
            text,
            (
                '    with Path(schema_path).open(encoding="utf8") as f:\n'
                "        schema_json = json.load(f)\n"
                "    return schema_json  # noqa: RET504\n"
            ),
            (
                "    schema_name = Path(schema_path).name\n"
                "    if schema_name in _STATICPYTHON_SCHEMAS:\n"
                "        return deepcopy(_STATICPYTHON_SCHEMAS[schema_name])\n"
                '    with Path(schema_path).open(encoding="utf8") as f:\n'
                "        schema_json = json.load(f)\n"
                "    return schema_json  # noqa: RET504\n"
            ),
            label="nbformat schema loader",
        )

    def patch_version(text: str) -> str:
        return replace_text_once(
            text,
            'import re\nfrom importlib.metadata import version\n\n__version__ = version("nbformat") or "0.0.0"\n',
            'import re\nfrom importlib.metadata import PackageNotFoundError, version\n\ntry:\n    __version__ = version("nbformat")\nexcept PackageNotFoundError:\n    __version__ = "0.0.0"\n',
            label="nbformat version fallback",
        )

    transform_source_text(context, "Lib/nbformat/validator.py", patch_validator)
    transform_source_text(context, "Lib/nbformat/_version.py", patch_version)


LIBRARY_INTEGRATION = simple_library(
    name="nbformat",
    overlay_entries=["Lib/nbformat"],
    post_patch_hooks=[embed_nbformat_schemas],
    verification_steps=[
        inline_verification_step(
            "nbformat-smoke",
            """
import io

import nbformat
from nbformat import v4

nb = v4.new_notebook()
nb.cells.append(v4.new_markdown_cell("# StaticPython"))
nb.cells.append(v4.new_code_cell("answer = 40 + 2"))

nbformat.validate(nb)
encoded = nbformat.writes(nb)
decoded = nbformat.reads(encoded, as_version=4)
assert decoded.cells[0].source == "# StaticPython"
assert decoded.cells[1].cell_type == "code"

buffer = io.StringIO()
nbformat.write(decoded, buffer)
buffer.seek(0)
roundtripped = nbformat.read(buffer, as_version=4)
assert roundtripped.nbformat == 4
assert nbformat.validator.isvalid(roundtripped)
""",
        )
    ],
)
