from libs import simple_library, write_source_text


def patch_protobuf_namespace(context):
    write_source_text(
        context,
        "Lib/google/__init__.py",
        "# Namespace package marker generated by StaticPython.\n",
    )


LIBRARY_INTEGRATION = simple_library(
    name="protobuf",
    project_name="protobuf",
    source_mapping={"google/protobuf": "Lib/google/protobuf"},
    python_packages=["google.protobuf"],
    post_patch_hooks=[patch_protobuf_namespace],
)
