from __future__ import annotations

import json

from libs import pypi_library, replace_text_once, source_path, transform_source_text, write_source_text


def embed_jsonschema_schemas(context) -> None:
    package_root = source_path(context, "Lib/jsonschema")
    schema_root = package_root / "schemas"
    if not schema_root.exists():
        return
    schemas = {}
    for path in sorted(schema_root.rglob("*")):
        if not path.is_file():
            continue
        schemas[path.relative_to(package_root).as_posix()] = json.loads(path.read_text(encoding="utf-8"))

    write_source_text(
        context,
        "Lib/jsonschema/_static_schemas.py",
        "# Generated by StaticPython; keeps jsonschema resource lookups usable after freezing.\n"
        + "SCHEMAS = "
        + repr(schemas)
        + "\n",
    )

    def patch_utils(text: str) -> str:
        text = replace_text_once(
            text,
            "import itertools\nimport json\nimport re\nimport sys\n",
            "import itertools\nimport json\nimport re\nimport sys\nfrom copy import deepcopy\n",
            label="jsonschema deepcopy import",
        )
        text = replace_text_once(
            text,
            '    import importlib_resources as resources  # type: ignore\n',
            '    import importlib_resources as resources  # type: ignore\n\nfrom ._static_schemas import SCHEMAS as _STATICPYTHON_SCHEMAS\n',
            label="jsonschema static schema import",
        )
        return replace_text_once(
            text,
            '    path = resources.files(__package__).joinpath(f"schemas/{name}.json")\n'
            '    data = path.read_text(encoding="utf-8")\n'
            "    return json.loads(data)\n",
            '    schema_path = f"schemas/{name}.json"\n'
            "    if schema_path in _STATICPYTHON_SCHEMAS:\n"
            "        return deepcopy(_STATICPYTHON_SCHEMAS[schema_path])\n"
            '    path = resources.files(__package__).joinpath(schema_path)\n'
            '    data = path.read_text(encoding="utf-8")\n'
            "    return json.loads(data)\n",
            label="jsonschema schema loader",
        )

    def patch_validators(text: str) -> str:
        text = replace_text_once(
            text,
            "    _validators,\n    exceptions,\n)\n",
            "    _validators,\n    exceptions,\n)\nfrom ._static_schemas import SCHEMAS as _STATICPYTHON_SCHEMAS\n",
            label="jsonschema validators static schema import",
        )
        return replace_text_once(
            text,
            "def _store_schema_list():\n"
            "    if not _VOCABULARIES:\n"
            "        package = _utils.resources.files(__package__)\n"
            '        for version in package.joinpath("schemas", "vocabularies").iterdir():\n'
            "            for path in version.iterdir():\n"
            "                vocabulary = json.loads(path.read_text())\n"
            '                _VOCABULARIES.append((vocabulary["$id"], vocabulary))\n'
            "    return [\n"
            "        (id, validator.META_SCHEMA) for id, validator in _META_SCHEMAS.items()\n"
            "    ] + _VOCABULARIES\n",
            "def _store_schema_list():\n"
            "    if not _VOCABULARIES:\n"
            "        embedded_vocabularies = [\n"
            "            _STATICPYTHON_SCHEMAS[path]\n"
            "            for path in sorted(_STATICPYTHON_SCHEMAS)\n"
            '            if path.startswith("schemas/vocabularies/")\n'
            "        ]\n"
            "        if embedded_vocabularies:\n"
            "            for vocabulary in embedded_vocabularies:\n"
            '                _VOCABULARIES.append((vocabulary["$id"], vocabulary))\n'
            "        else:\n"
            "            package = _utils.resources.files(__package__)\n"
            '            for version in package.joinpath("schemas").joinpath("vocabularies").iterdir():\n'
            "                for path in version.iterdir():\n"
            "                    vocabulary = json.loads(path.read_text())\n"
            '                    _VOCABULARIES.append((vocabulary["$id"], vocabulary))\n'
            "    return [\n"
            "        (id, validator.META_SCHEMA) for id, validator in _META_SCHEMAS.items()\n"
            "    ] + _VOCABULARIES\n",
            label="jsonschema vocabulary loader",
        )

    transform_source_text(context, "Lib/jsonschema/_utils.py", patch_utils)
    transform_source_text(context, "Lib/jsonschema/validators.py", patch_validators)


LIBRARY_INTEGRATION = pypi_library(
    name="jsonschema",
    release_version="4.17.3",
    source_mapping={
        "jsonschema": "Lib/jsonschema",
    },
    python_packages=["jsonschema"],
    post_patch_hooks=[embed_jsonschema_schemas],
)
